-- =============================================================================
-- Phase GL-4 — Seed canonical public GEOlibrary content
--
-- Source: geoverze-public-main/src/features/library/data/{creators,articles,collections}.ts
-- Generated by: supabase/scripts/generate_gl4_seed.ts
--
-- Idempotent: ON CONFLICT DO NOTHING guards on all inserts.
-- Requires: 20260901120000_phase_gl1_library_foundation.sql
-- =============================================================================

-- Creators (featured_collection_slug deferred until collections exist)
insert into public.library_creators (handle, display_name, role, bio, art_key, verified, location, joined_at, featured_collection_slug, user_id)
values ('atlas-studio', 'Atlas Studio', 'Cartography collective', 'A three-person studio drawing bronze relief plates and writing the notes that go with them. Obsessed with borders, coastlines and the stories behind survey lines.', 'creator-atlas-studio', true, 'Lisbon, Portugal', '2024-03-11', null, null)
on conflict (handle) do nothing;

insert into public.library_creators (handle, display_name, role, bio, art_key, verified, location, joined_at, featured_collection_slug, user_id)
values ('meridian', 'Meridian', 'Physical geographer', 'Writes about mountains, plates and the slow machinery of the planet. Former field surveyor, current explainer of things that take a million years.', 'creator-meridian', true, 'Innsbruck, Austria', '2024-06-02', null, null)
on conflict (handle) do nothing;

insert into public.library_creators (handle, display_name, role, bio, art_key, verified, location, joined_at, featured_collection_slug, user_id)
values ('delta-notes', 'Delta Notes', 'Hydrology writer', 'Rivers, deltas, basins and the politics of water. If it flows downhill, there is probably an article about it here.', 'creator-delta-notes', false, 'Dhaka, Bangladesh', '2025-01-19', null, null)
on conflict (handle) do nothing;

insert into public.library_creators (handle, display_name, role, bio, art_key, verified, location, joined_at, featured_collection_slug, user_id)
values ('terra-lingua', 'Terra Lingua', 'Culture & language desk', 'Language families, scripts, currencies and the everyday culture that maps rarely show. Written with linguists, checked by travellers.', 'creator-terra-lingua', true, 'Nairobi, Kenya', '2024-11-08', null, null)
on conflict (handle) do nothing;

insert into public.library_creators (handle, display_name, role, bio, art_key, verified, location, joined_at, featured_collection_slug, user_id)
values ('heritage-desk', 'Heritage Desk', 'UNESCO correspondent', 'Documenting protected places, why they earned protection and what still threatens them. One site at a time, in plain language.', 'creator-heritage-desk', false, 'Kyoto, Japan', '2025-04-27', null, null)
on conflict (handle) do nothing;

-- Collections
insert into public.library_collections (id, slug, title, description, art_key, subject_category, continent, curator_handle, featured, status, published_at)
values ('23548ce8-24c5-4a06-af38-1db629780058', 'countries-of-europe', 'Countries of Europe', 'Forty-four states, their capitals, borders and the treaties that drew them. Start with the microstates and work outward.', 'collection-countries-of-europe', 'countries', 'europe', 'atlas-studio', true, 'published', now())
on conflict (slug) do nothing;

insert into public.library_collections (id, slug, title, description, art_key, subject_category, continent, curator_handle, featured, status, published_at)
values ('1f407c90-95df-406c-abac-31a0aa32ed19', 'world-capitals', 'World Capitals', 'Seats of government, why they sit where they do, and the handful of countries that could not settle on one.', 'collection-world-capitals', 'capitals', 'global', 'atlas-studio', true, 'published', now())
on conflict (slug) do nothing;

insert into public.library_collections (id, slug, title, description, art_key, subject_category, continent, curator_handle, featured, status, published_at)
values ('46e4447e-f552-491e-adf9-820030ad0569', 'great-rivers', 'Great Rivers', 'Basins, discharge, deltas and disputes. The systems that decide where civilisations sit.', 'collection-great-rivers', 'oceans', 'global', 'delta-notes', true, 'published', now())
on conflict (slug) do nothing;

insert into public.library_collections (id, slug, title, description, art_key, subject_category, continent, curator_handle, featured, status, published_at)
values ('c7e88766-e7f2-43c9-a03b-d01fd489aba2', 'mountain-ranges', 'Mountain Ranges', 'Uplift, erosion and the ranges that manufacture their own weather systems.', 'collection-mountain-ranges', 'physical', 'global', 'meridian', true, 'published', now())
on conflict (slug) do nothing;

insert into public.library_collections (id, slug, title, description, art_key, subject_category, continent, curator_handle, featured, status, published_at)
values ('46beb383-5da5-4df3-abed-add06ac4f048', 'unesco-heritage', 'UNESCO Heritage', 'How places earn protection, what protection actually means, and which sites are currently at risk.', 'collection-unesco-heritage', 'heritage', 'global', 'heritage-desk', false, 'published', now())
on conflict (slug) do nothing;

insert into public.library_collections (id, slug, title, description, art_key, subject_category, continent, curator_handle, featured, status, published_at)
values ('412107af-9a6b-4912-ac30-4c1d70dc20d5', 'geography-basics', 'Geography Basics', 'The starting shelf: reading maps, reading flags, and the vocabulary everything else assumes.', 'collection-geography-basics', 'basics', 'global', 'terra-lingua', true, 'published', now())
on conflict (slug) do nothing;

insert into public.library_collections (id, slug, title, description, art_key, subject_category, continent, curator_handle, featured, status, published_at)
values ('8f4419e8-b4b6-476b-aec7-cde2cc530a10', 'climate-change', 'Climate Change', 'Where the climate signal is already visible on the map, region by region.', 'collection-climate-change', 'climate', 'global', 'terra-lingua', false, 'published', now())
on conflict (slug) do nothing;

insert into public.library_collections (id, slug, title, description, art_key, subject_category, continent, curator_handle, featured, status, published_at)
values ('2c644fba-17a3-4445-ad76-aef1e77e63f2', 'natural-wonders', 'Natural Wonders', 'Landforms and phenomena that draw people from every continent, and the geology behind them.', 'collection-natural-wonders', 'landmarks', 'global', 'heritage-desk', false, 'published', now())
on conflict (slug) do nothing;

-- Creator featured collections (after collection slugs exist)
update public.library_creators set featured_collection_slug = 'countries-of-europe' where handle = 'atlas-studio' and featured_collection_slug is distinct from 'countries-of-europe';
update public.library_creators set featured_collection_slug = 'mountain-ranges' where handle = 'meridian' and featured_collection_slug is distinct from 'mountain-ranges';
update public.library_creators set featured_collection_slug = 'great-rivers' where handle = 'delta-notes' and featured_collection_slug is distinct from 'great-rivers';
update public.library_creators set featured_collection_slug = 'geography-basics' where handle = 'terra-lingua' and featured_collection_slug is distinct from 'geography-basics';
update public.library_creators set featured_collection_slug = 'unesco-heritage' where handle = 'heritage-desk' and featured_collection_slug is distinct from 'unesco-heritage';

-- Resources
insert into public.library_resources (
  id, slug, title, dek, resource_kind, subject_category, continent, difficulty,
  read_time_minutes, language, country, region, tags, status, featured,
  author_handle, cover_art_key, cover_label, seo_meta_title, seo_meta_description,
  seo_canonical_path, seo_og_title, seo_og_description, seo_keywords, published_at
) values (
  '50bd1167-a678-4775-a465-01676c970de1', 'why-some-countries-have-two-capitals', 'Why some countries have two capitals', 'Bolivia, South Africa, the Netherlands — splitting a capital is more common, and more deliberate, than most maps suggest.',
  'article', 'capitals', 'global', 'beginner',
  6, 'English', null, null, array['capitals', 'government', 'politics'],
  'published', false, 'atlas-studio', null, null,
  'Why some countries have two capitals — GEOlibrary', 'Bolivia, South Africa, the Netherlands — splitting a capital is more common, and more deliberate, than most maps suggest.',
  '/geolibrary/article/why-some-countries-have-two-capitals', 'Why some countries have two capitals', 'Bolivia, South Africa, the Netherlands — splitting a capital is more common, and more deliberate, than most maps suggest.',
  array['capitals', 'government', 'politics'], '2026-08-01T12:00:00Z'::timestamptz
) on conflict (slug) do nothing;

insert into public.library_resources (
  id, slug, title, dek, resource_kind, subject_category, continent, difficulty,
  read_time_minutes, language, country, region, tags, status, featured,
  author_handle, cover_art_key, cover_label, seo_meta_title, seo_meta_description,
  seo_canonical_path, seo_og_title, seo_og_description, seo_keywords, published_at
) values (
  'a9170d28-bfc1-4c25-ab53-7a72eabf735a', 'how-the-himalayas-keep-growing', 'How the Himalayas keep growing', 'India is still driving north at roughly the speed your fingernails grow, and the roof of the world is the receipt.',
  'article', 'physical', 'asia', 'intermediate',
  9, 'English', null, null, array['himalaya', 'mountains', 'tectonics', 'everest'],
  'published', false, 'meridian', null, null,
  'How the Himalayas keep growing — GEOlibrary', 'India is still driving north at roughly the speed your fingernails grow, and the roof of the world is the receipt.',
  '/geolibrary/article/how-the-himalayas-keep-growing', 'How the Himalayas keep growing', 'India is still driving north at roughly the speed your fingernails grow, and the roof of the world is the receipt.',
  array['himalaya', 'mountains', 'tectonics', 'everest'], '2026-07-28T12:00:00Z'::timestamptz
) on conflict (slug) do nothing;

insert into public.library_resources (
  id, slug, title, dek, resource_kind, subject_category, continent, difficulty,
  read_time_minutes, language, country, region, tags, status, featured,
  author_handle, cover_art_key, cover_label, seo_meta_title, seo_meta_description,
  seo_canonical_path, seo_og_title, seo_og_description, seo_keywords, published_at
) values (
  '0fdde805-c5f5-4e26-ad65-ee25b509065d', 'the-sahel-explained', 'The Sahel, explained', 'A 5,000 km belt of semi-arid land where the Sahara negotiates with the savanna — and where climate and politics meet head-on.',
  'article', 'climate', 'africa', 'intermediate',
  8, 'English', null, null, array['sahel', 'africa', 'climate', 'desert'],
  'published', false, 'terra-lingua', null, null,
  'The Sahel, explained — GEOlibrary', 'A 5,000 km belt of semi-arid land where the Sahara negotiates with the savanna — and where climate and politics meet head-on.',
  '/geolibrary/article/the-sahel-explained', 'The Sahel, explained', 'A 5,000 km belt of semi-arid land where the Sahara negotiates with the savanna — and where climate and politics meet head-on.',
  array['sahel', 'africa', 'climate', 'desert'], '2026-07-21T12:00:00Z'::timestamptz
) on conflict (slug) do nothing;

insert into public.library_resources (
  id, slug, title, dek, resource_kind, subject_category, continent, difficulty,
  read_time_minutes, language, country, region, tags, status, featured,
  author_handle, cover_art_key, cover_label, seo_meta_title, seo_meta_description,
  seo_canonical_path, seo_og_title, seo_og_description, seo_keywords, published_at
) values (
  '3bb6a8ad-0560-43de-a9f1-81969c0a4c6c', 'the-straightest-borders-on-earth', 'The straightest borders on Earth', 'Where a boundary follows a parallel instead of a river, someone drew it in a room far away.',
  'article', 'countries', 'global', 'beginner',
  7, 'English', null, null, array['borders', 'colonial', 'surveying'],
  'published', false, 'atlas-studio', null, null,
  'The straightest borders on Earth — GEOlibrary', 'Where a boundary follows a parallel instead of a river, someone drew it in a room far away.',
  '/geolibrary/article/the-straightest-borders-on-earth', 'The straightest borders on Earth', 'Where a boundary follows a parallel instead of a river, someone drew it in a room far away.',
  array['borders', 'colonial', 'surveying'], '2026-07-14T12:00:00Z'::timestamptz
) on conflict (slug) do nothing;

insert into public.library_resources (
  id, slug, title, dek, resource_kind, subject_category, continent, difficulty,
  read_time_minutes, language, country, region, tags, status, featured,
  author_handle, cover_art_key, cover_label, seo_meta_title, seo_meta_description,
  seo_canonical_path, seo_og_title, seo_og_description, seo_keywords, published_at
) values (
  '684b559f-5a9b-4469-ad23-e14dd3b2761a', 'reading-a-flag-in-thirty-seconds', 'Reading a flag in thirty seconds', 'Colours, charges and proportions carry more information than most people expect. Here is the grammar.',
  'article', 'flags', 'global', 'beginner',
  4, 'English', null, null, array['flags', 'vexillology', 'symbols'],
  'published', false, 'atlas-studio', null, null,
  'Reading a flag in thirty seconds — GEOlibrary', 'Colours, charges and proportions carry more information than most people expect. Here is the grammar.',
  '/geolibrary/article/reading-a-flag-in-thirty-seconds', 'Reading a flag in thirty seconds', 'Colours, charges and proportions carry more information than most people expect. Here is the grammar.',
  array['flags', 'vexillology', 'symbols'], '2026-07-09T12:00:00Z'::timestamptz
) on conflict (slug) do nothing;

insert into public.library_resources (
  id, slug, title, dek, resource_kind, subject_category, continent, difficulty,
  read_time_minutes, language, country, region, tags, status, featured,
  author_handle, cover_art_key, cover_label, seo_meta_title, seo_meta_description,
  seo_canonical_path, seo_og_title, seo_og_description, seo_keywords, published_at
) values (
  '451449b7-d9e1-4a55-ac87-26a008bca624', 'the-nile-and-the-amazon', 'The Nile and the Amazon: which is longest?', 'A measurement argument that has run for a century, and why the answer depends on where you decide a river begins.',
  'article', 'oceans', 'global', 'intermediate',
  8, 'English', null, null, array['rivers', 'nile', 'amazon', 'hydrology'],
  'published', false, 'delta-notes', null, null,
  'The Nile and the Amazon: which is longest? — GEOlibrary', 'A measurement argument that has run for a century, and why the answer depends on where you decide a river begins.',
  '/geolibrary/article/the-nile-and-the-amazon', 'The Nile and the Amazon: which is longest?', 'A measurement argument that has run for a century, and why the answer depends on where you decide a river begins.',
  array['rivers', 'nile', 'amazon', 'hydrology'], '2026-07-02T12:00:00Z'::timestamptz
) on conflict (slug) do nothing;

insert into public.library_resources (
  id, slug, title, dek, resource_kind, subject_category, continent, difficulty,
  read_time_minutes, language, country, region, tags, status, featured,
  author_handle, cover_art_key, cover_label, seo_meta_title, seo_meta_description,
  seo_canonical_path, seo_og_title, seo_og_description, seo_keywords, published_at
) values (
  '65b1d8ac-5bf0-4209-aa0a-437f1d99fcc6', 'how-unesco-picks-a-world-heritage-site', 'How UNESCO picks a World Heritage site', 'Ten criteria, one committee and a long queue. Inside the process that turns a place into a protected one.',
  'article', 'heritage', 'global', 'beginner',
  5, 'English', null, null, array['unesco', 'heritage', 'conservation'],
  'published', false, 'heritage-desk', null, null,
  'How UNESCO picks a World Heritage site — GEOlibrary', 'Ten criteria, one committee and a long queue. Inside the process that turns a place into a protected one.',
  '/geolibrary/article/how-unesco-picks-a-world-heritage-site', 'How UNESCO picks a World Heritage site', 'Ten criteria, one committee and a long queue. Inside the process that turns a place into a protected one.',
  array['unesco', 'heritage', 'conservation'], '2026-06-25T12:00:00Z'::timestamptz
) on conflict (slug) do nothing;

insert into public.library_resources (
  id, slug, title, dek, resource_kind, subject_category, continent, difficulty,
  read_time_minutes, language, country, region, tags, status, featured,
  author_handle, cover_art_key, cover_label, seo_meta_title, seo_meta_description,
  seo_canonical_path, seo_og_title, seo_og_description, seo_keywords, published_at
) values (
  '1497d5c2-d8ec-49f6-a3d2-9adc33d5b738', 'why-there-are-five-oceans-now', 'Why there are five oceans now', 'The Southern Ocean was recognised in 2021, and the reason is a current rather than a coastline.',
  'article', 'oceans', 'antarctica', 'beginner',
  5, 'English', null, null, array['oceans', 'southern ocean', 'antarctica', 'currents'],
  'published', false, 'delta-notes', null, null,
  'Why there are five oceans now — GEOlibrary', 'The Southern Ocean was recognised in 2021, and the reason is a current rather than a coastline.',
  '/geolibrary/article/why-there-are-five-oceans-now', 'Why there are five oceans now', 'The Southern Ocean was recognised in 2021, and the reason is a current rather than a coastline.',
  array['oceans', 'southern ocean', 'antarctica', 'currents'], '2026-06-18T12:00:00Z'::timestamptz
) on conflict (slug) do nothing;

insert into public.library_resources (
  id, slug, title, dek, resource_kind, subject_category, continent, difficulty,
  read_time_minutes, language, country, region, tags, status, featured,
  author_handle, cover_art_key, cover_label, seo_meta_title, seo_meta_description,
  seo_canonical_path, seo_og_title, seo_og_description, seo_keywords, published_at
) values (
  '5db8f91d-4f91-46ed-a2e7-ab1a5a902e02', 'languages-that-cross-the-most-borders', 'Languages that cross the most borders', 'Official status is politics; everyday speech is geography. The two rarely line up.',
  'article', 'culture', 'global', 'intermediate',
  7, 'English', null, null, array['languages', 'culture', 'linguistics'],
  'published', false, 'terra-lingua', null, null,
  'Languages that cross the most borders — GEOlibrary', 'Official status is politics; everyday speech is geography. The two rarely line up.',
  '/geolibrary/article/languages-that-cross-the-most-borders', 'Languages that cross the most borders', 'Official status is politics; everyday speech is geography. The two rarely line up.',
  array['languages', 'culture', 'linguistics'], '2026-06-10T12:00:00Z'::timestamptz
) on conflict (slug) do nothing;

insert into public.library_resources (
  id, slug, title, dek, resource_kind, subject_category, continent, difficulty,
  read_time_minutes, language, country, region, tags, status, featured,
  author_handle, cover_art_key, cover_label, seo_meta_title, seo_meta_description,
  seo_canonical_path, seo_og_title, seo_og_description, seo_keywords, published_at
) values (
  '9c7ebb85-91c4-4d75-a0c6-44d4749a14cb', 'what-a-currency-tells-you-about-a-country', 'What a currency tells you about a country', 'Pegs, unions and dollarisation are geography problems disguised as monetary ones.',
  'article', 'culture', 'global', 'advanced',
  11, 'English', null, null, array['currencies', 'economics', 'trade'],
  'published', false, 'terra-lingua', null, null,
  'What a currency tells you about a country — GEOlibrary', 'Pegs, unions and dollarisation are geography problems disguised as monetary ones.',
  '/geolibrary/article/what-a-currency-tells-you-about-a-country', 'What a currency tells you about a country', 'Pegs, unions and dollarisation are geography problems disguised as monetary ones.',
  array['currencies', 'economics', 'trade'], '2026-06-03T12:00:00Z'::timestamptz
) on conflict (slug) do nothing;

insert into public.library_resources (
  id, slug, title, dek, resource_kind, subject_category, continent, difficulty,
  read_time_minutes, language, country, region, tags, status, featured,
  author_handle, cover_art_key, cover_label, seo_meta_title, seo_meta_description,
  seo_canonical_path, seo_og_title, seo_og_description, seo_keywords, published_at
) values (
  '2be8f9b1-0851-4e70-abb9-ee41ac89443c', 'the-landmarks-everyone-misplaces', 'The landmarks everyone misplaces', 'Machu Picchu is not in the Andes'' highest range, and the Sphinx is younger than you think.',
  'article', 'landmarks', 'global', 'beginner',
  6, 'English', null, null, array['landmarks', 'monuments', 'misconceptions'],
  'published', false, 'heritage-desk', null, null,
  'The landmarks everyone misplaces — GEOlibrary', 'Machu Picchu is not in the Andes'' highest range, and the Sphinx is younger than you think.',
  '/geolibrary/article/the-landmarks-everyone-misplaces', 'The landmarks everyone misplaces', 'Machu Picchu is not in the Andes'' highest range, and the Sphinx is younger than you think.',
  array['landmarks', 'monuments', 'misconceptions'], '2026-05-27T12:00:00Z'::timestamptz
) on conflict (slug) do nothing;

insert into public.library_resources (
  id, slug, title, dek, resource_kind, subject_category, continent, difficulty,
  read_time_minutes, language, country, region, tags, status, featured,
  author_handle, cover_art_key, cover_label, seo_meta_title, seo_meta_description,
  seo_canonical_path, seo_og_title, seo_og_description, seo_keywords, published_at
) values (
  '2f6080fb-cf80-48cd-abd4-77705d073778', 'how-to-read-a-topographic-map', 'How to read a topographic map', 'Contours, intervals and the three shapes that tell you everything about terrain.',
  'article', 'basics', 'global', 'beginner',
  5, 'English', null, null, array['maps', 'contours', 'basics', 'navigation'],
  'published', false, 'meridian', null, null,
  'How to read a topographic map — GEOlibrary', 'Contours, intervals and the three shapes that tell you everything about terrain.',
  '/geolibrary/article/how-to-read-a-topographic-map', 'How to read a topographic map', 'Contours, intervals and the three shapes that tell you everything about terrain.',
  array['maps', 'contours', 'basics', 'navigation'], '2026-05-20T12:00:00Z'::timestamptz
) on conflict (slug) do nothing;

insert into public.library_resources (
  id, slug, title, dek, resource_kind, subject_category, continent, difficulty,
  read_time_minutes, language, country, region, tags, status, featured,
  author_handle, cover_art_key, cover_label, seo_meta_title, seo_meta_description,
  seo_canonical_path, seo_og_title, seo_og_description, seo_keywords, published_at
) values (
  '66cc187f-e761-47c7-a671-6d9889663ddd', 'europes-smallest-states', 'Europe''s smallest states', 'Six microstates, six very different reasons for surviving the age of empires intact.',
  'article', 'countries', 'europe', 'beginner',
  6, 'English', null, null, array['europe', 'microstates', 'countries', 'vatican'],
  'published', false, 'atlas-studio', null, null,
  'Europe''s smallest states — GEOlibrary', 'Six microstates, six very different reasons for surviving the age of empires intact.',
  '/geolibrary/article/europes-smallest-states', 'Europe''s smallest states', 'Six microstates, six very different reasons for surviving the age of empires intact.',
  array['europe', 'microstates', 'countries', 'vatican'], '2026-05-12T12:00:00Z'::timestamptz
) on conflict (slug) do nothing;

insert into public.library_resources (
  id, slug, title, dek, resource_kind, subject_category, continent, difficulty,
  read_time_minutes, language, country, region, tags, status, featured,
  author_handle, cover_art_key, cover_label, seo_meta_title, seo_meta_description,
  seo_canonical_path, seo_og_title, seo_og_description, seo_keywords, published_at
) values (
  '208596fd-e5a2-4ca6-a358-d48f52296de9', 'megacities-and-the-limits-of-growth', 'Megacities and the limits of growth', 'Thirty-three cities now pass ten million people. Water, not land, decides which of them keep growing.',
  'article', 'capitals', 'asia', 'advanced',
  12, 'English', null, null, array['cities', 'urban', 'population', 'water'],
  'published', false, 'meridian', null, null,
  'Megacities and the limits of growth — GEOlibrary', 'Thirty-three cities now pass ten million people. Water, not land, decides which of them keep growing.',
  '/geolibrary/article/megacities-and-the-limits-of-growth', 'Megacities and the limits of growth', 'Thirty-three cities now pass ten million people. Water, not land, decides which of them keep growing.',
  array['cities', 'urban', 'population', 'water'], '2026-05-04T12:00:00Z'::timestamptz
) on conflict (slug) do nothing;

-- Resource blocks
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('807eacc4-731c-4575-a5a1-202101320024', '50bd1167-a678-4775-a465-01676c970de1', 0, 'paragraph', '{"text":"A capital is a job description, not a single city. Somewhere has to host the legislature, somewhere the executive, somewhere the highest court — and nothing in international law says those places must share a postcode."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('2b44be8e-4e38-429d-a849-808b04ebda75', '50bd1167-a678-4775-a465-01676c970de1', 1, 'heading', '{"id":"the-split","text":"The three-way split"}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('6d21921b-4849-4a2a-ab17-fecf7fbb2186', '50bd1167-a678-4775-a465-01676c970de1', 2, 'paragraph', '{"text":"South Africa is the textbook case. Pretoria holds the executive, Cape Town the parliament and Bloemfontein the judiciary. The arrangement was a compromise at union in 1910, and it survived because moving any branch would cost a province its status."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('675b00b2-3b14-427b-a750-2ad6b048d847', '50bd1167-a678-4775-a465-01676c970de1', 3, 'list', '{"items":["Bolivia: Sucre is constitutional, La Paz is where the government sits.","Netherlands: Amsterdam is the constitutional capital, The Hague the seat of government.","Malaysia: Kuala Lumpur is the capital, Putrajaya the administrative centre.","Tanzania: Dodoma is official, Dar es Salaam remains the commercial anchor."],"ordered":false}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('d9653189-2dae-4a6a-ab9c-b62fe49aeb88', '50bd1167-a678-4775-a465-01676c970de1', 4, 'facts', '{"title":"At a glance","facts":[{"label":"Countries with split functions","value":"12+"},{"label":"Oldest arrangement","value":"South Africa, 1910"},{"label":"Most recent move","value":"Indonesia, Nusantara"},{"label":"Quiz appearances","value":"High"}]}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('4cbdc987-b005-45d5-a9b4-e522d47f26e6', '50bd1167-a678-4775-a465-01676c970de1', 5, 'heading', '{"id":"why-it-happens","text":"Why it happens"}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('5a04d5ea-4d95-4961-a3bd-deecf2047d6b', '50bd1167-a678-4775-a465-01676c970de1', 6, 'paragraph', '{"text":"Three forces recur: federation compromises, decongestion of an overgrown primate city, and symbolic relocation toward a geographic centre. Brazil built Brasília for the third reason and got the second as a bonus."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('0922b2d5-8757-4941-a913-2aedefda3c69', '50bd1167-a678-4775-a465-01676c970de1', 7, 'quote', '{"text":"A capital city is the argument a country is having with itself, written in concrete.","attribution":"Atlas Studio field notes"}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('9ae540b2-2115-4d33-ab7a-880f9443f77e', '50bd1167-a678-4775-a465-01676c970de1', 8, 'map', '{"region":"Capitals","caption":"Interactive capitals map — arriving with the GEOverze map engine."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('14d19d7f-298d-4af1-acf8-6ce40cadf162', '50bd1167-a678-4775-a465-01676c970de1', 9, 'didYouKnow', '{"text":"Every figure in this entry is cross-linked to the same dataset that powers Capitals questions in Let''s Play, so reading here directly sharpens your quiz accuracy."}'::jsonb)
on conflict (resource_id, position) do nothing;

insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('5a8c887c-0b1e-4863-ae22-2069be50ccb0', 'a9170d28-bfc1-4c25-ab53-7a72eabf735a', 0, 'paragraph', '{"text":"Fifty million years ago the Indian plate was an island heading north across the Tethys Ocean. It hit Eurasia, and because both plates were continental crust, neither could sink. Everything went up instead."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('da77956d-dd81-484b-a06e-67610abed31f', 'a9170d28-bfc1-4c25-ab53-7a72eabf735a', 1, 'heading', '{"id":"collision","text":"A collision with nowhere to go"}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('6d6713b1-a5e2-4245-aedd-816e5ea1bd01', 'a9170d28-bfc1-4c25-ab53-7a72eabf735a', 2, 'paragraph', '{"text":"Convergence continues at about 45 mm a year. Roughly a third of that is absorbed by the range itself, which is why the Himalayas gain a few millimetres of height annually — while erosion quietly claws some of it back."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('4dad181d-7b06-4186-aa31-7a4e557ab1a3', 'a9170d28-bfc1-4c25-ab53-7a72eabf735a', 3, 'image', '{"art":"article-himalaya-uplift","caption":"Uplift and erosion in balance across the main range."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('a0c481bb-c479-4d0c-a521-4980ccac558f', 'a9170d28-bfc1-4c25-ab53-7a72eabf735a', 4, 'facts', '{"title":"The numbers","facts":[{"label":"Convergence rate","value":"~45 mm / year"},{"label":"Uplift","value":"~5 mm / year"},{"label":"Peaks above 8,000 m","value":"10 of 14"},{"label":"Age of collision","value":"~50 million years"}]}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('791e8f8b-1798-4455-a93d-a16081b2c381', 'a9170d28-bfc1-4c25-ab53-7a72eabf735a', 5, 'heading', '{"id":"monsoon","text":"The range that makes the weather"}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('c6fae8f5-3302-481f-aec1-7eaa50d787e3', 'a9170d28-bfc1-4c25-ab53-7a72eabf735a', 6, 'paragraph', '{"text":"The wall does more than exist: it blocks cold Central Asian air from reaching the subcontinent and forces the summer monsoon to dump its moisture on the southern slopes. Half of Asia''s agriculture depends on that mechanism."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('87fb5fff-dfe6-4e0c-a0b1-ecaa3499c09e', 'a9170d28-bfc1-4c25-ab53-7a72eabf735a', 7, 'list', '{"items":["Ten of the world''s fourteen 8,000 m peaks sit on the Himalayan arc.","The range feeds the Indus, Ganges and Brahmaputra systems.","Glacial retreat is now measurable decade to decade."],"ordered":false}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('3c0662ce-59bf-464b-aa91-0f67b7f90c91', 'a9170d28-bfc1-4c25-ab53-7a72eabf735a', 8, 'map', '{"region":"Mountain ranges","caption":"Interactive mountain ranges map — arriving with the GEOverze map engine."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('cccec8c4-336e-4491-a23d-d18941a874dd', 'a9170d28-bfc1-4c25-ab53-7a72eabf735a', 9, 'didYouKnow', '{"text":"Every figure in this entry is cross-linked to the same dataset that powers Mountain ranges questions in Let''s Play, so reading here directly sharpens your quiz accuracy."}'::jsonb)
on conflict (resource_id, position) do nothing;

insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('1b731f87-8bb7-40f2-a34d-6821e461ed5a', '0fdde805-c5f5-4e26-ad65-ee25b509065d', 0, 'paragraph', '{"text":"The word comes from the Arabic sāḥil, meaning shore. Seen from the desert, the Sahel is exactly that: the coastline of a sea of sand, where scrub gives way to grass and rain becomes possible again."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('d26eed64-cf77-4763-a35e-55eea889d1bb', '0fdde805-c5f5-4e26-ad65-ee25b509065d', 1, 'heading', '{"id":"geography","text":"Where it actually is"}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('d5d8a371-4763-49d4-a0ef-a5b8285c696b', '0fdde805-c5f5-4e26-ad65-ee25b509065d', 2, 'paragraph', '{"text":"It runs from Senegal on the Atlantic to Eritrea on the Red Sea, crossing Mauritania, Mali, Burkina Faso, Niger, Nigeria, Chad and Sudan. Rainfall averages 200–600 mm a year, almost all of it in a single short season."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('65537ba3-5562-483b-ab57-43716036aff6', '0fdde805-c5f5-4e26-ad65-ee25b509065d', 3, 'map', '{"region":"Sahel belt","caption":"The Sahel belt across eleven countries — map engine pending."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('d8b0c990-17c3-44f1-af16-fa2a08f91717', '0fdde805-c5f5-4e26-ad65-ee25b509065d', 4, 'facts', '{"title":"Key figures","facts":[{"label":"Length","value":"~5,400 km"},{"label":"Annual rainfall","value":"200 – 600 mm"},{"label":"Countries crossed","value":"11"},{"label":"Population","value":"~150 million"}]}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('a50f6218-b770-4f21-a47e-d2b1220f701c', '0fdde805-c5f5-4e26-ad65-ee25b509065d', 5, 'heading', '{"id":"great-green-wall","text":"The Great Green Wall"}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('35b1f320-e403-45cd-ae99-bd3a66743d42', '0fdde805-c5f5-4e26-ad65-ee25b509065d', 6, 'paragraph', '{"text":"Launched in 2007, the plan was a literal wall of trees across the continent. It has since become something better: a mosaic of restored farmland, water-harvesting bunds and community land rights that works with existing agriculture rather than around it."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('3a60ebde-285f-4263-a3ec-528661e59cf9', '0fdde805-c5f5-4e26-ad65-ee25b509065d', 7, 'quote', '{"text":"The Sahel is not the Sahara advancing. It is rainfall variability meeting land under pressure.","attribution":"Terra Lingua"}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('b4fb88df-a1ba-4414-a39c-7551b3129048', '0fdde805-c5f5-4e26-ad65-ee25b509065d', 8, 'map', '{"region":"Climate","caption":"Interactive climate map — arriving with the GEOverze map engine."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('52c7309a-3d23-429b-a095-a270df71a6ff', '0fdde805-c5f5-4e26-ad65-ee25b509065d', 9, 'didYouKnow', '{"text":"Every figure in this entry is cross-linked to the same dataset that powers Climate questions in Let''s Play, so reading here directly sharpens your quiz accuracy."}'::jsonb)
on conflict (resource_id, position) do nothing;

insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('566ce2c8-fe3b-4525-af32-0992a409ca2b', '3bb6a8ad-0560-43de-a9f1-81969c0a4c6c', 0, 'paragraph', '{"text":"Natural borders wander. They follow watersheds, rivers and ridgelines because those are the things people historically could not cross. Straight borders are a signature of cartography imposed from outside."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('a7e15e18-92f8-4bfb-a5c6-348ea73b3e46', '3bb6a8ad-0560-43de-a9f1-81969c0a4c6c', 1, 'heading', '{"id":"the-longest","text":"The longest straight line"}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('5ddad405-3a89-40be-a4f7-a510093309c6', '3bb6a8ad-0560-43de-a9f1-81969c0a4c6c', 2, 'paragraph', '{"text":"The 49th parallel carries the Canada–United States boundary for nearly 2,000 km. Surveying it took decades, and the crews cut a six-metre clearing through forest — the Slash — that is still maintained today."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('828abc08-83f1-453f-a990-1a601f1f118b', '3bb6a8ad-0560-43de-a9f1-81969c0a4c6c', 3, 'list', '{"items":["Egypt–Sudan: the 22nd parallel, with the disputed Hala''ib triangle as its footnote.","Algeria–Mali–Niger: desert lines drawn by compass bearing.","Western Australia: a state boundary on the 129th meridian."],"ordered":false}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('a9afc65a-e4ec-4239-a848-3240bbc63604', '3bb6a8ad-0560-43de-a9f1-81969c0a4c6c', 4, 'image', '{"art":"article-straight-borders","caption":"Parallels and meridians as political instruments."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('dfa98c18-f82b-4b68-abb8-96f35ad64d2c', '3bb6a8ad-0560-43de-a9f1-81969c0a4c6c', 5, 'heading', '{"id":"consequences","text":"What straight lines cost"}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('614a67d3-f12e-4a21-a20a-9d71021c547d', '3bb6a8ad-0560-43de-a9f1-81969c0a4c6c', 6, 'paragraph', '{"text":"A line drawn without reference to who lives there splits language groups, grazing routes and watersheds. Many long-running boundary disputes trace directly to a nineteenth-century ruler on a small-scale map."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('bbebca6e-5517-4056-aed5-2f2c6cd787b5', '3bb6a8ad-0560-43de-a9f1-81969c0a4c6c', 7, 'map', '{"region":"Countries","caption":"Interactive countries map — arriving with the GEOverze map engine."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('6ce3d12c-a22c-4895-a2c6-330af68a260e', '3bb6a8ad-0560-43de-a9f1-81969c0a4c6c', 8, 'didYouKnow', '{"text":"Every figure in this entry is cross-linked to the same dataset that powers Countries questions in Let''s Play, so reading here directly sharpens your quiz accuracy."}'::jsonb)
on conflict (resource_id, position) do nothing;

insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('90a67e81-027e-44e5-a86d-7097e56be404', '684b559f-5a9b-4469-ad23-e14dd3b2761a', 0, 'paragraph', '{"text":"Flags are compressed history. Once you know the recurring families — tricolours, Nordic crosses, pan-African and pan-Arab palettes — most of the world''s 195 national flags become guessable rather than memorisable."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('6307f723-bd67-4d61-a42e-8d8c0cdf4152', '684b559f-5a9b-4469-ad23-e14dd3b2761a', 1, 'heading', '{"id":"families","text":"The five big families"}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('d1dd3c35-c068-44eb-a048-6d12c75e78c5', '684b559f-5a9b-4469-ad23-e14dd3b2761a', 2, 'list', '{"items":["Tricolours: France''s 1794 design copied across Europe, Africa and the Americas.","Nordic crosses: an off-centre cross, always signalling the Nordic sphere.","Pan-African: green, gold and red, from Ethiopia outward.","Pan-Arab: black, white, green and red from the 1916 Arab Revolt.","Union-derived: a canton in the top-left, tracing British administration."],"ordered":true}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('8a9e1cc5-9ca2-4f1a-a07e-c7230475cbc5', '684b559f-5a9b-4469-ad23-e14dd3b2761a', 3, 'facts', '{"title":"Vexillology quick sheet","facts":[{"label":"Most common colour","value":"Red"},{"label":"Only non-rectangular","value":"Nepal"},{"label":"Identical pairs","value":"Monaco & Indonesia"},{"label":"Newest national flag","value":"2021, Afghanistan"}]}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('a766bbd3-abef-4ddf-a404-9f739a596ffa', '684b559f-5a9b-4469-ad23-e14dd3b2761a', 4, 'didYouKnow', '{"text":"Nepal''s flag is the only national flag that is not a quadrilateral — its two stacked pennants represent the Himalayas and the country''s two dominant faiths."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('782b94f6-20f5-430e-affd-d1ccccb92770', '684b559f-5a9b-4469-ad23-e14dd3b2761a', 5, 'map', '{"region":"Flags","caption":"Interactive flags map — arriving with the GEOverze map engine."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('56370607-d43c-4a85-aae4-cc5a9e25ecab', '684b559f-5a9b-4469-ad23-e14dd3b2761a', 6, 'didYouKnow', '{"text":"Every figure in this entry is cross-linked to the same dataset that powers Flags questions in Let''s Play, so reading here directly sharpens your quiz accuracy."}'::jsonb)
on conflict (resource_id, position) do nothing;

insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('3344501d-4598-4a8d-a8f1-fceef2148bc6', '451449b7-d9e1-4a55-ac87-26a008bca624', 0, 'paragraph', '{"text":"Length sounds like a fact. For rivers it is a decision: which headwater counts, how you handle a braided delta, and what resolution your coastline data uses."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('3ec39625-b6d4-4967-a600-3165d383eb6d', '451449b7-d9e1-4a55-ac87-26a008bca624', 1, 'heading', '{"id":"the-case","text":"The case for each"}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('c4af7243-6132-442b-a26f-20057f964672', '451449b7-d9e1-4a55-ac87-26a008bca624', 2, 'paragraph', '{"text":"The Nile is conventionally 6,650 km from Lake Victoria''s feeders to the Mediterranean. The Amazon is usually given as 6,400 km, but expeditions tracing it to the Mantaro headwaters in Peru push it past 6,900 km."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('d6f15ea3-64a6-496c-ab5b-f6612cb7e1e6', '451449b7-d9e1-4a55-ac87-26a008bca624', 3, 'facts', '{"title":"Not close on discharge","facts":[{"label":"Amazon discharge","value":"~209,000 m³/s"},{"label":"Nile discharge","value":"~2,800 m³/s"},{"label":"Amazon basin","value":"7.0 million km²"},{"label":"Nile basin","value":"3.4 million km²"}]}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('4499bcab-a8d2-4977-ae77-d25542b78a52', '451449b7-d9e1-4a55-ac87-26a008bca624', 4, 'paragraph', '{"text":"By volume there is no contest. The Amazon carries roughly a fifth of all river water reaching the ocean, and its plume is detectable hundreds of kilometres out to sea."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('ba84b782-8dc3-4c99-acc6-1692b7f5b6a6', '451449b7-d9e1-4a55-ac87-26a008bca624', 5, 'quote', '{"text":"Ask which river is longest and you get an answer about methodology, not geography.","attribution":"Delta Notes"}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('68aa6f51-a2a2-4bdf-a464-2e2b4d026441', '451449b7-d9e1-4a55-ac87-26a008bca624', 6, 'map', '{"region":"Rivers","caption":"Interactive rivers map — arriving with the GEOverze map engine."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('f28077db-b65e-49f7-a794-e3e01f30d2a3', '451449b7-d9e1-4a55-ac87-26a008bca624', 7, 'didYouKnow', '{"text":"Every figure in this entry is cross-linked to the same dataset that powers Rivers questions in Let''s Play, so reading here directly sharpens your quiz accuracy."}'::jsonb)
on conflict (resource_id, position) do nothing;

insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('d1e86fa9-a8f6-44d0-a7bd-06d90a787914', '65b1d8ac-5bf0-4209-aa0a-437f1d99fcc6', 0, 'paragraph', '{"text":"A site must show what the convention calls Outstanding Universal Value: significance so exceptional it transcends national boundaries. In practice that means meeting at least one of ten criteria, six cultural and four natural."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('2a062bc3-ba22-42bf-a292-ff8db6a721aa', '65b1d8ac-5bf0-4209-aa0a-437f1d99fcc6', 1, 'heading', '{"id":"the-route","text":"The route to inscription"}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('77b25a23-f98d-43d2-af08-ea7a8cd1a05d', '65b1d8ac-5bf0-4209-aa0a-437f1d99fcc6', 2, 'list', '{"items":["The state party adds the site to its tentative list.","A full nomination dossier is prepared, often over years.","ICOMOS or IUCN carries out an independent evaluation.","The World Heritage Committee votes at its annual session."],"ordered":true}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('833088a4-b0c2-430c-a092-709fb48cbec6', '65b1d8ac-5bf0-4209-aa0a-437f1d99fcc6', 3, 'facts', '{"title":"The register today","facts":[{"label":"Total sites","value":"1,200+"},{"label":"Cultural","value":"~933"},{"label":"Natural","value":"~227"},{"label":"In danger","value":"~56"}]}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('f0aa79fc-3ac3-43b6-a44c-0567d4d7bd67', '65b1d8ac-5bf0-4209-aa0a-437f1d99fcc6', 4, 'didYouKnow', '{"text":"Sites can be removed. Dresden''s Elbe Valley lost its status in 2009 after a four-lane bridge was built through the protected landscape."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('c16a389b-a8cb-45da-ae72-a128880278d6', '65b1d8ac-5bf0-4209-aa0a-437f1d99fcc6', 5, 'map', '{"region":"UNESCO heritage","caption":"Interactive unesco heritage map — arriving with the GEOverze map engine."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('84a7dcaf-080a-4b27-a7c7-8b227f806753', '65b1d8ac-5bf0-4209-aa0a-437f1d99fcc6', 6, 'didYouKnow', '{"text":"Every figure in this entry is cross-linked to the same dataset that powers UNESCO heritage questions in Let''s Play, so reading here directly sharpens your quiz accuracy."}'::jsonb)
on conflict (resource_id, position) do nothing;

insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('1cf3827b-6a32-4cc1-a0f8-11fe3f84b538', '1497d5c2-d8ec-49f6-a3d2-9adc33d5b738', 0, 'paragraph', '{"text":"Every other ocean is defined by the land around it. The Southern Ocean is defined by water: the Antarctic Circumpolar Current, which circles the continent uninterrupted and keeps its cold water distinct from what lies north."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('72114120-77cb-4a53-a02f-1bef60029cf6', '1497d5c2-d8ec-49f6-a3d2-9adc33d5b738', 1, 'heading', '{"id":"boundary","text":"Where it starts"}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('72d425c4-e937-488b-af54-866ab21787c9', '1497d5c2-d8ec-49f6-a3d2-9adc33d5b738', 2, 'paragraph', '{"text":"The working boundary is 60° south. North of it the water warms and mixes with the Atlantic, Pacific and Indian; south of it the circumpolar current dominates and the ecosystem changes with it."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('bad8e6a5-fd83-48b7-a9d4-5690cf0bf515', '1497d5c2-d8ec-49f6-a3d2-9adc33d5b738', 3, 'facts', '{"title":"The five","facts":[{"label":"Pacific","value":"165.2 million km²"},{"label":"Atlantic","value":"106.5 million km²"},{"label":"Indian","value":"70.6 million km²"},{"label":"Southern","value":"21.9 million km²"}]}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('13a3874c-c7a3-4167-aaf5-75dd11e644c0', '1497d5c2-d8ec-49f6-a3d2-9adc33d5b738', 4, 'map', '{"region":"Southern Ocean","caption":"The 60° south boundary and the circumpolar current."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('bad336aa-db7e-440c-aae6-5255a77c82c0', '1497d5c2-d8ec-49f6-a3d2-9adc33d5b738', 5, 'map', '{"region":"Oceans","caption":"Interactive oceans map — arriving with the GEOverze map engine."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('0aa5bd1b-c613-4c37-a06f-aaa93b705bd6', '1497d5c2-d8ec-49f6-a3d2-9adc33d5b738', 6, 'didYouKnow', '{"text":"Every figure in this entry is cross-linked to the same dataset that powers Oceans questions in Let''s Play, so reading here directly sharpens your quiz accuracy."}'::jsonb)
on conflict (resource_id, position) do nothing;

insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('70a3c9e8-c541-4587-a795-583fbef0e891', '5db8f91d-4f91-46ed-a2e7-ab1a5a902e02', 0, 'paragraph', '{"text":"Around 7,000 languages are spoken today, but fewer than a hundred hold official status anywhere. The gap between those numbers is where most of the world''s linguistic geography lives."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('3211990d-921f-4e30-a7a1-a645c60d5dff', '5db8f91d-4f91-46ed-a2e7-ab1a5a902e02', 1, 'heading', '{"id":"widest","text":"The widest reach"}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('5b68e0fe-7b2c-4474-a4c4-aa48de7e84f3', '5db8f91d-4f91-46ed-a2e7-ab1a5a902e02', 2, 'list', '{"items":["English: official or co-official in 58 countries.","French: 29 countries across five continents.","Arabic: 25 countries, with dialect continua that ignore borders entirely.","Spanish: 21 countries, remarkably mutually intelligible."],"ordered":false}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('1cb6f10c-84c9-4166-a320-059f9734e00b', '5db8f91d-4f91-46ed-a2e7-ab1a5a902e02', 3, 'paragraph', '{"text":"Reach is not the same as speaker count. Mandarin has more native speakers than English but official status in only a handful of states, because its distribution is concentrated rather than colonial."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('6056820a-1e7f-464b-ad08-86ac481765bb', '5db8f91d-4f91-46ed-a2e7-ab1a5a902e02', 4, 'didYouKnow', '{"text":"Papua New Guinea has over 840 living languages — roughly 12% of the world''s total in 0.3% of its land area."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('7df67fa6-9f3a-4aea-a0bd-f557058aab5f', '5db8f91d-4f91-46ed-a2e7-ab1a5a902e02', 5, 'map', '{"region":"Cultures","caption":"Interactive cultures map — arriving with the GEOverze map engine."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('31b9e1d2-9bf3-49a2-a43d-2641df8df698', '5db8f91d-4f91-46ed-a2e7-ab1a5a902e02', 6, 'didYouKnow', '{"text":"Every figure in this entry is cross-linked to the same dataset that powers Cultures questions in Let''s Play, so reading here directly sharpens your quiz accuracy."}'::jsonb)
on conflict (resource_id, position) do nothing;

insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('538b7350-a5a3-4c50-a3e7-23946e709a6c', '9c7ebb85-91c4-4d75-a0c6-44d4749a14cb', 0, 'paragraph', '{"text":"There are about 180 recognised currencies for 195 countries. The shortfall is the interesting part: shared unions, adopted foreign notes and hard pegs each say something about trade, size and trust."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('5c6318a1-14b9-44ee-a2b1-17ab8641c190', '9c7ebb85-91c4-4d75-a0c6-44d4749a14cb', 1, 'heading', '{"id":"unions","text":"Currency unions"}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('6f3afb69-64af-4086-a75f-6be285399519', '9c7ebb85-91c4-4d75-a0c6-44d4749a14cb', 2, 'paragraph', '{"text":"The euro is the famous one, but the CFA franc covers fourteen African states across two zones, and the Eastern Caribbean dollar binds eight island economies to a single central bank."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('e642b732-4ff5-44dd-a413-296d08e73aed', '9c7ebb85-91c4-4d75-a0c6-44d4749a14cb', 3, 'heading', '{"id":"dollarisation","text":"Adopting someone else''s money"}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('c4323a7f-bb83-4b26-ad2f-e2431eb21598', '9c7ebb85-91c4-4d75-a0c6-44d4749a14cb', 4, 'list', '{"items":["Ecuador, El Salvador and Panama use the US dollar outright.","Montenegro and Kosovo use the euro without being in the eurozone.","Several Pacific states use the Australian or New Zealand dollar."],"ordered":false}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('66b0d60e-de7e-4081-a6b9-6d91849964fc', '9c7ebb85-91c4-4d75-a0c6-44d4749a14cb', 5, 'facts', '{"title":"Currency map","facts":[{"label":"Recognised currencies","value":"~180"},{"label":"Countries using the euro","value":"20 official"},{"label":"CFA franc states","value":"14"},{"label":"Fully dollarised","value":"7+"}]}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('1214bbe1-0ee2-4411-a28c-5424552d2b6a', '9c7ebb85-91c4-4d75-a0c6-44d4749a14cb', 6, 'quote', '{"text":"A currency border is the most honest border there is — it shows where trust actually stops.","attribution":"Terra Lingua"}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('7312f3e4-6fdc-420d-aaae-d869f5c72642', '9c7ebb85-91c4-4d75-a0c6-44d4749a14cb', 7, 'map', '{"region":"Currencies","caption":"Interactive currencies map — arriving with the GEOverze map engine."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('ab8aafae-0516-43ca-aa5e-4a7cfecdbbb6', '9c7ebb85-91c4-4d75-a0c6-44d4749a14cb', 8, 'didYouKnow', '{"text":"Every figure in this entry is cross-linked to the same dataset that powers Currencies questions in Let''s Play, so reading here directly sharpens your quiz accuracy."}'::jsonb)
on conflict (resource_id, position) do nothing;

insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('2f431c22-f73f-4d9e-a3c8-484f0d2e3264', '2be8f9b1-0851-4e70-abb9-ee41ac89443c', 0, 'paragraph', '{"text":"Famous places accumulate folklore faster than facts. These are the six that cause the most wrong answers in Let''s Play rounds, and the corrections that stick."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('b2c443c5-b1ed-4c45-a075-c0795f84444f', '2be8f9b1-0851-4e70-abb9-ee41ac89443c', 1, 'heading', '{"id":"six","text":"Six corrections"}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('e928dde7-02bc-4a7a-a062-bedde775817a', '2be8f9b1-0851-4e70-abb9-ee41ac89443c', 2, 'list', '{"items":["Machu Picchu sits at 2,430 m — lower than Cusco, which is at 3,400 m.","The Great Wall is not visible to the naked eye from orbit.","Stonehenge predates the pyramids of Giza.","The Leaning Tower began tilting during construction, not centuries later.","Mount Everest is not the furthest point from Earth''s centre — Chimborazo is.","Angkor Wat is Hindu in origin, Buddhist by later adaptation."],"ordered":true}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('5260785a-a6b9-4ddb-a14a-1b0e4b3c03d3', '2be8f9b1-0851-4e70-abb9-ee41ac89443c', 3, 'image', '{"art":"article-landmark-myths","caption":"Six landmarks, six persistent misreadings."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('09ea39cc-a104-49ec-a9a4-b4c92940c478', '2be8f9b1-0851-4e70-abb9-ee41ac89443c', 4, 'map', '{"region":"Landmarks","caption":"Interactive landmarks map — arriving with the GEOverze map engine."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('66ff7c26-fe1f-41f6-adaa-0b0121d32bff', '2be8f9b1-0851-4e70-abb9-ee41ac89443c', 5, 'didYouKnow', '{"text":"Every figure in this entry is cross-linked to the same dataset that powers Landmarks questions in Let''s Play, so reading here directly sharpens your quiz accuracy."}'::jsonb)
on conflict (resource_id, position) do nothing;

insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('d4dbdd64-f6a8-4ad8-aa90-43d2c347a95c', '2f6080fb-cf80-48cd-abd4-77705d073778', 0, 'paragraph', '{"text":"A contour line joins points of equal elevation. That single rule generates every pattern on a topographic sheet, and three of those patterns cover most of what you need in the field."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('7c7e764e-5a00-4bf5-ad6d-eafb846fa342', '2f6080fb-cf80-48cd-abd4-77705d073778', 1, 'heading', '{"id":"patterns","text":"The three shapes"}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('a2bd4d1d-b901-42b4-a6ff-1ac008c09d32', '2f6080fb-cf80-48cd-abd4-77705d073778', 2, 'list', '{"items":["Concentric closed loops: a hill, with the smallest ring at the summit.","V-shapes pointing uphill: a valley, with the V aiming upstream.","Lines packed tightly together: a steep face; widely spaced means gentle ground."],"ordered":false}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('2b92d9eb-adab-4d40-aedf-6ab41b51f770', '2f6080fb-cf80-48cd-abd4-77705d073778', 3, 'facts', '{"title":"Reading essentials","facts":[{"label":"Standard interval","value":"10 m or 20 m"},{"label":"Index contours","value":"Every 5th line, labelled"},{"label":"Grid north vs true north","value":"Check the declination"},{"label":"Scale on hiking sheets","value":"1:25,000"}]}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('0cf00351-2bc7-4233-af19-28d117b8143e', '2f6080fb-cf80-48cd-abd4-77705d073778', 4, 'didYouKnow', '{"text":"Contour lines never cross. Where terrain overhangs, cartographers switch to dashed lines rather than break the rule."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('9300030c-0f47-43ea-a789-5a77f7a1b461', '2f6080fb-cf80-48cd-abd4-77705d073778', 5, 'map', '{"region":"Geography basics","caption":"Interactive geography basics map — arriving with the GEOverze map engine."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('8f0fd636-6c13-4b86-ad2c-ba8e280ae009', '2f6080fb-cf80-48cd-abd4-77705d073778', 6, 'didYouKnow', '{"text":"Every figure in this entry is cross-linked to the same dataset that powers Geography basics questions in Let''s Play, so reading here directly sharpens your quiz accuracy."}'::jsonb)
on conflict (resource_id, position) do nothing;

insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('2580f896-10d5-4a3f-a073-14d77d66735e', '66cc187f-e761-47c7-a671-6d9889663ddd', 0, 'paragraph', '{"text":"Vatican City, Monaco, San Marino, Liechtenstein, Malta and Andorra together would fit inside a mid-sized city. Each survived by being useful, defensible or simply too small to bother annexing."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('0ab90c77-1fe5-4a7f-a2c4-d784851aa0f9', '66cc187f-e761-47c7-a671-6d9889663ddd', 1, 'facts', '{"title":"By area","facts":[{"label":"Vatican City","value":"0.49 km²"},{"label":"Monaco","value":"2.02 km²"},{"label":"San Marino","value":"61 km²"},{"label":"Liechtenstein","value":"160 km²"}]}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('b1a98b9f-9b5b-4c0a-af31-5209e6c68d29', '66cc187f-e761-47c7-a671-6d9889663ddd', 2, 'heading', '{"id":"how","text":"How they held on"}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('3868f4f8-6d94-41e6-ab4e-77080ea43f4e', '66cc187f-e761-47c7-a671-6d9889663ddd', 3, 'paragraph', '{"text":"San Marino claims continuous independence since 301 CE by staying strategically irrelevant on a defensible mountain. Liechtenstein was bought as a package of estates specifically to qualify for a seat in the Imperial Diet."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('8074f41b-9b5c-4137-a043-e24510cdabd0', '66cc187f-e761-47c7-a671-6d9889663ddd', 4, 'map', '{"region":"Countries","caption":"Interactive countries map — arriving with the GEOverze map engine."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('66ab52e0-fe9d-44bf-af29-5ad55b05fbb5', '66cc187f-e761-47c7-a671-6d9889663ddd', 5, 'didYouKnow', '{"text":"Every figure in this entry is cross-linked to the same dataset that powers Countries questions in Let''s Play, so reading here directly sharpens your quiz accuracy."}'::jsonb)
on conflict (resource_id, position) do nothing;

insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('f1ece37d-b7e8-4fe9-a3ba-0b170761e084', '208596fd-e5a2-4ca6-a358-d48f52296de9', 0, 'paragraph', '{"text":"A megacity is any urban agglomeration above ten million people. In 1975 there were three. Today there are more than thirty, and two thirds of them are in Asia."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('a0cad1c9-a437-4c02-a5f7-2852d2767ab3', '208596fd-e5a2-4ca6-a358-d48f52296de9', 1, 'heading', '{"id":"constraint","text":"The binding constraint"}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('3dc0dd43-c4a3-4900-afc8-917a0e74f2a6', '208596fd-e5a2-4ca6-a358-d48f52296de9', 2, 'paragraph', '{"text":"Housing and transport are solvable with capital. Water is not. Mexico City is sinking as it drains its aquifer, Jakarta is moving its capital function partly because of subsidence, and Cape Town has already run a countdown to Day Zero."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('5c730b45-4df8-4e2b-a3f6-7e7e2bda597f', '208596fd-e5a2-4ca6-a358-d48f52296de9', 3, 'facts', '{"title":"Largest agglomerations","facts":[{"label":"Tokyo","value":"~37 million"},{"label":"Delhi","value":"~33 million"},{"label":"Shanghai","value":"~29 million"},{"label":"Dhaka","value":"~23 million"}]}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('46105d39-0939-4a0e-a574-eb60b4afb4a0', '208596fd-e5a2-4ca6-a358-d48f52296de9', 4, 'map', '{"region":"Global megacities","caption":"Thirty-three agglomerations above ten million."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('28d52247-671c-40e5-a80b-b0d49c0f7d5f', '208596fd-e5a2-4ca6-a358-d48f52296de9', 5, 'quote', '{"text":"Cities do not stop growing when they run out of land. They stop when they run out of water.","attribution":"Meridian"}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('253ef647-aa5e-4d88-a915-43b8f42145be', '208596fd-e5a2-4ca6-a358-d48f52296de9', 6, 'map', '{"region":"Capitals","caption":"Interactive capitals map — arriving with the GEOverze map engine."}'::jsonb)
on conflict (resource_id, position) do nothing;
insert into public.library_resource_blocks (id, resource_id, position, kind, payload)
values ('585cba89-bc87-4eae-ad32-36708e186645', '208596fd-e5a2-4ca6-a358-d48f52296de9', 7, 'didYouKnow', '{"text":"Every figure in this entry is cross-linked to the same dataset that powers Capitals questions in Let''s Play, so reading here directly sharpens your quiz accuracy."}'::jsonb)
on conflict (resource_id, position) do nothing;

-- Collection items
insert into public.library_collection_items (collection_id, resource_id, position)
values ('23548ce8-24c5-4a06-af38-1db629780058', '66cc187f-e761-47c7-a671-6d9889663ddd', 0)
on conflict (collection_id, resource_id) do nothing;
insert into public.library_collection_items (collection_id, resource_id, position)
values ('23548ce8-24c5-4a06-af38-1db629780058', '3bb6a8ad-0560-43de-a9f1-81969c0a4c6c', 1)
on conflict (collection_id, resource_id) do nothing;
insert into public.library_collection_items (collection_id, resource_id, position)
values ('23548ce8-24c5-4a06-af38-1db629780058', '684b559f-5a9b-4469-ad23-e14dd3b2761a', 2)
on conflict (collection_id, resource_id) do nothing;

insert into public.library_collection_items (collection_id, resource_id, position)
values ('1f407c90-95df-406c-abac-31a0aa32ed19', '50bd1167-a678-4775-a465-01676c970de1', 0)
on conflict (collection_id, resource_id) do nothing;
insert into public.library_collection_items (collection_id, resource_id, position)
values ('1f407c90-95df-406c-abac-31a0aa32ed19', '208596fd-e5a2-4ca6-a358-d48f52296de9', 1)
on conflict (collection_id, resource_id) do nothing;

insert into public.library_collection_items (collection_id, resource_id, position)
values ('46e4447e-f552-491e-adf9-820030ad0569', '451449b7-d9e1-4a55-ac87-26a008bca624', 0)
on conflict (collection_id, resource_id) do nothing;
insert into public.library_collection_items (collection_id, resource_id, position)
values ('46e4447e-f552-491e-adf9-820030ad0569', '1497d5c2-d8ec-49f6-a3d2-9adc33d5b738', 1)
on conflict (collection_id, resource_id) do nothing;

insert into public.library_collection_items (collection_id, resource_id, position)
values ('c7e88766-e7f2-43c9-a03b-d01fd489aba2', 'a9170d28-bfc1-4c25-ab53-7a72eabf735a', 0)
on conflict (collection_id, resource_id) do nothing;
insert into public.library_collection_items (collection_id, resource_id, position)
values ('c7e88766-e7f2-43c9-a03b-d01fd489aba2', '2f6080fb-cf80-48cd-abd4-77705d073778', 1)
on conflict (collection_id, resource_id) do nothing;

insert into public.library_collection_items (collection_id, resource_id, position)
values ('46beb383-5da5-4df3-abed-add06ac4f048', '65b1d8ac-5bf0-4209-aa0a-437f1d99fcc6', 0)
on conflict (collection_id, resource_id) do nothing;
insert into public.library_collection_items (collection_id, resource_id, position)
values ('46beb383-5da5-4df3-abed-add06ac4f048', '2be8f9b1-0851-4e70-abb9-ee41ac89443c', 1)
on conflict (collection_id, resource_id) do nothing;

insert into public.library_collection_items (collection_id, resource_id, position)
values ('412107af-9a6b-4912-ac30-4c1d70dc20d5', '2f6080fb-cf80-48cd-abd4-77705d073778', 0)
on conflict (collection_id, resource_id) do nothing;
insert into public.library_collection_items (collection_id, resource_id, position)
values ('412107af-9a6b-4912-ac30-4c1d70dc20d5', '684b559f-5a9b-4469-ad23-e14dd3b2761a', 1)
on conflict (collection_id, resource_id) do nothing;
insert into public.library_collection_items (collection_id, resource_id, position)
values ('412107af-9a6b-4912-ac30-4c1d70dc20d5', '1497d5c2-d8ec-49f6-a3d2-9adc33d5b738', 2)
on conflict (collection_id, resource_id) do nothing;

insert into public.library_collection_items (collection_id, resource_id, position)
values ('8f4419e8-b4b6-476b-aec7-cde2cc530a10', '0fdde805-c5f5-4e26-ad65-ee25b509065d', 0)
on conflict (collection_id, resource_id) do nothing;
insert into public.library_collection_items (collection_id, resource_id, position)
values ('8f4419e8-b4b6-476b-aec7-cde2cc530a10', '208596fd-e5a2-4ca6-a358-d48f52296de9', 1)
on conflict (collection_id, resource_id) do nothing;

insert into public.library_collection_items (collection_id, resource_id, position)
values ('2c644fba-17a3-4445-ad76-aef1e77e63f2', '2be8f9b1-0851-4e70-abb9-ee41ac89443c', 0)
on conflict (collection_id, resource_id) do nothing;
insert into public.library_collection_items (collection_id, resource_id, position)
values ('2c644fba-17a3-4445-ad76-aef1e77e63f2', 'a9170d28-bfc1-4c25-ab53-7a72eabf735a', 1)
on conflict (collection_id, resource_id) do nothing;
insert into public.library_collection_items (collection_id, resource_id, position)
values ('2c644fba-17a3-4445-ad76-aef1e77e63f2', '451449b7-d9e1-4a55-ac87-26a008bca624', 2)
on conflict (collection_id, resource_id) do nothing;

-- Verification counts
do $$
declare
  c_creators int;
  c_resources int;
  c_blocks int;
  c_collections int;
  c_items int;
begin
  select count(*) into c_creators from public.library_creators;
  select count(*) into c_resources from public.library_resources;
  select count(*) into c_blocks from public.library_resource_blocks;
  select count(*) into c_collections from public.library_collections;
  select count(*) into c_items from public.library_collection_items;
  if c_creators < 5 then raise exception 'GL-4 seed: expected >= 5 creators, got %', c_creators; end if;
  if c_resources < 14 then raise exception 'GL-4 seed: expected >= 14 resources, got %', c_resources; end if;
  if c_collections < 8 then raise exception 'GL-4 seed: expected >= 8 collections, got %', c_collections; end if;
  if c_blocks < 50 then raise exception 'GL-4 seed: expected >= 50 blocks, got %', c_blocks; end if;
  if c_items < 10 then raise exception 'GL-4 seed: expected >= 10 collection items, got %', c_items; end if;
  raise notice 'GL-4 seed OK: creators=%, resources=%, blocks=%, collections=%, items=%', c_creators, c_resources, c_blocks, c_collections, c_items;
end $$;