/**
 * Generates GL-4 canonical GEOlibrary seed migration from public mock data.
 *
 * Run from repo root:
 *   npx tsx supabase/scripts/generate_gl4_seed.ts
 */
import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { ARTICLES } from "../../geoverze-main/geoverze-public-main/src/features/library/data/articles.ts";
import { COLLECTIONS } from "../../geoverze-main/geoverze-public-main/src/features/library/data/collections.ts";
import { CREATORS } from "../../geoverze-main/geoverze-public-main/src/features/library/data/creators.ts";
import type { ArticleBlock } from "../../geoverze-main/geoverze-public-main/src/features/library/data/articles.ts";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = join(__dirname, "../migrations/20260901130000_phase_gl4_library_seed.sql");

function stableUuid(namespace: string, key: string): string {
  const hash = createHash("sha256").update(`${namespace}:${key}`).digest("hex");
  return `${hash.slice(0, 8)}-${hash.slice(8, 12)}-4${hash.slice(13, 16)}-a${hash.slice(17, 20)}-${hash.slice(20, 32)}`;
}

function sqlStr(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlTextArray(values: readonly string[]): string {
  if (values.length === 0) return "array[]::text[]";
  return `array[${values.map((v) => sqlStr(v)).join(", ")}]`;
}

function sqlJson(value: unknown): string {
  return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;
}

function blockPayload(block: ArticleBlock): Record<string, unknown> {
  switch (block.kind) {
    case "heading":
      return { id: block.id, text: block.text };
    case "paragraph":
      return { text: block.text };
    case "list":
      return { items: block.items, ordered: block.ordered ?? false };
    case "quote":
      return { text: block.text, attribution: block.attribution ?? null };
    case "image":
      return { art: block.art, caption: block.caption };
    case "map":
      return { region: block.region, caption: block.caption };
    case "facts":
      return { title: block.title, facts: block.facts };
    case "didYouKnow":
      return { text: block.text };
  }
}

const lines: string[] = [
  "-- =============================================================================",
  "-- Phase GL-4 — Seed canonical public GEOlibrary content",
  "--",
  "-- Source: geoverze-public-main/src/features/library/data/{creators,articles,collections}.ts",
  "-- Generated by: supabase/scripts/generate_gl4_seed.ts",
  "--",
  "-- Idempotent: ON CONFLICT DO NOTHING guards on all inserts.",
  "-- Requires: 20260901120000_phase_gl1_library_foundation.sql",
  "-- =============================================================================",
  "",
  "-- Creators (featured_collection_slug deferred until collections exist)",
];

for (const creator of CREATORS) {
  lines.push(
    `insert into public.library_creators (handle, display_name, role, bio, art_key, verified, location, joined_at, featured_collection_slug, user_id)`,
    `values (${sqlStr(creator.handle)}, ${sqlStr(creator.name)}, ${sqlStr(creator.role)}, ${sqlStr(creator.bio)}, ${sqlStr(creator.art)}, ${creator.verified}, ${creator.location ? sqlStr(creator.location) : "null"}, ${sqlStr(creator.joinedAt)}, null, null)`,
    `on conflict (handle) do nothing;`,
    "",
  );
}

lines.push("-- Collections");
for (const collection of COLLECTIONS) {
  const id = stableUuid("library_collection", collection.slug);
  lines.push(
    `insert into public.library_collections (id, slug, title, description, art_key, subject_category, continent, curator_handle, featured, status, published_at)`,
    `values ('${id}', ${sqlStr(collection.slug)}, ${sqlStr(collection.title)}, ${sqlStr(collection.description)}, ${sqlStr(collection.art)}, ${sqlStr(collection.category)}, ${sqlStr(collection.continent)}, ${sqlStr(collection.curator)}, ${collection.featured}, 'published', now())`,
    `on conflict (slug) do nothing;`,
    "",
  );
}

lines.push("-- Creator featured collections (after collections FK targets exist)");
for (const creator of CREATORS) {
  lines.push(
    `update public.library_creators`,
    `set featured_collection_slug = ${sqlStr(creator.featuredCollection)}`,
    `where handle = ${sqlStr(creator.handle)}`,
    `  and featured_collection_slug is distinct from ${sqlStr(creator.featuredCollection)};`,
    "",
  );
}

lines.push("-- Resources");
for (const article of ARTICLES) {
  const id = stableUuid("library_resource", article.slug);
  const seoTitle = `${article.title} — GEOlibrary`;
  lines.push(
    `insert into public.library_resources (`,
    `  id, slug, title, dek, resource_kind, subject_category, continent, difficulty,`,
    `  read_time_minutes, language, country, region, tags, status, featured,`,
    `  author_handle, cover_art_key, cover_label, seo_meta_title, seo_meta_description,`,
    `  seo_canonical_path, seo_og_title, seo_og_description, seo_keywords, published_at`,
    `) values (`,
    `  '${id}', ${sqlStr(article.slug)}, ${sqlStr(article.title)}, ${sqlStr(article.dek)},`,
    `  'article', ${sqlStr(article.category)}, ${sqlStr(article.continent)}, ${sqlStr(article.difficulty)},`,
    `  ${article.minutes}, 'English', null, null, ${sqlTextArray(article.tags)},`,
    `  'published', false, ${sqlStr(article.creator)}, null, null,`,
    `  ${sqlStr(seoTitle)}, ${sqlStr(article.dek)},`,
    `  ${sqlStr(`/geolibrary/article/${article.slug}`)}, ${sqlStr(article.title)}, ${sqlStr(article.dek)},`,
    `  ${sqlTextArray(article.tags)}, ${sqlStr(`${article.publishedAt}T12:00:00Z`)}::timestamptz`,
    `) on conflict (slug) do nothing;`,
    "",
  );
}

lines.push("-- Resource blocks");
for (const article of ARTICLES) {
  const resourceId = stableUuid("library_resource", article.slug);
  article.blocks.forEach((block, position) => {
    const blockId = stableUuid("library_block", `${article.slug}:${position}`);
    lines.push(
      `insert into public.library_resource_blocks (id, resource_id, position, kind, payload)`,
      `values ('${blockId}', '${resourceId}', ${position}, '${block.kind}', ${sqlJson(blockPayload(block))})`,
      `on conflict (resource_id, position) do nothing;`,
    );
  });
  lines.push("");
}

lines.push("-- Collection items");
for (const collection of COLLECTIONS) {
  const collectionId = stableUuid("library_collection", collection.slug);
  collection.articles.forEach((articleSlug, position) => {
    const resourceId = stableUuid("library_resource", articleSlug);
    lines.push(
      `insert into public.library_collection_items (collection_id, resource_id, position)`,
      `values ('${collectionId}', '${resourceId}', ${position})`,
      `on conflict (collection_id, resource_id) do nothing;`,
    );
  });
  lines.push("");
}

lines.push(
  "-- Verification counts",
  "do $$",
  "declare",
  "  c_creators int;",
  "  c_resources int;",
  "  c_blocks int;",
  "  c_collections int;",
  "  c_items int;",
  "begin",
  "  select count(*) into c_creators from public.library_creators;",
  "  select count(*) into c_resources from public.library_resources;",
  "  select count(*) into c_blocks from public.library_resource_blocks;",
  "  select count(*) into c_collections from public.library_collections;",
  "  select count(*) into c_items from public.library_collection_items;",
  "  if c_creators < 5 then raise exception 'GL-4 seed: expected >= 5 creators, got %', c_creators; end if;",
  "  if c_resources < 14 then raise exception 'GL-4 seed: expected >= 14 resources, got %', c_resources; end if;",
  "  if c_collections < 8 then raise exception 'GL-4 seed: expected >= 8 collections, got %', c_collections; end if;",
  "  if c_blocks < 50 then raise exception 'GL-4 seed: expected >= 50 blocks, got %', c_blocks; end if;",
  "  if c_items < 10 then raise exception 'GL-4 seed: expected >= 10 collection items, got %', c_items; end if;",
  "  raise notice 'GL-4 seed OK: creators=%, resources=%, blocks=%, collections=%, items=%', c_creators, c_resources, c_blocks, c_collections, c_items;",
  "end $$;",
);

writeFileSync(OUT, lines.join("\n"), "utf8");
console.log(`Wrote ${OUT}`);
console.log(
  `Counts: creators=${CREATORS.length}, articles=${ARTICLES.length}, collections=${COLLECTIONS.length}, blocks=${ARTICLES.reduce((n, a) => n + a.blocks.length, 0)}, items=${COLLECTIONS.reduce((n, c) => n + c.articles.length, 0)}`,
);
