/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as CreatorsRouteImport } from './routes/creators'
import { Route as CreditsRouteImport } from './routes/credits'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ModerationRouteImport } from './routes/moderation'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as QuestionsRouteImport } from './routes/questions'
import { Route as QuizzesRouteImport } from './routes/quizzes'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StoreRouteImport } from './routes/store'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as SupportRouteImport } from './routes/support'
import { Route as UsersRouteImport } from './routes/users'
import { Route as AnalyticsIndexRouteImport } from './routes/analytics.index'
import { Route as AnalyticsReportsRouteImport } from './routes/analytics.reports'
import { Route as CreatorsIndexRouteImport } from './routes/creators.index'
import { Route as CreatorsCreatorIdRouteImport } from './routes/creators.$creatorId'
import { Route as CreditsIndexRouteImport } from './routes/credits.index'
import { Route as CreditsAdjustmentsRouteImport } from './routes/credits.adjustments'
import { Route as CreditsAnalyticsRouteImport } from './routes/credits.analytics'
import { Route as CreditsRulesRouteImport } from './routes/credits.rules'
import { Route as LibraryIndexRouteImport } from './routes/library.index'
import { Route as LibraryResourceIdRouteImport } from './routes/library.$resourceId'
import { Route as LibraryNewRouteImport } from './routes/library.new'
import { Route as ModerationIndexRouteImport } from './routes/moderation.index'
import { Route as ModerationCommunityRouteImport } from './routes/moderation.community'
import { Route as ModerationCreatorsRouteImport } from './routes/moderation.creators'
import { Route as ModerationQuizzesRouteImport } from './routes/moderation.quizzes'
import { Route as QuizzesIndexRouteImport } from './routes/quizzes.index'
import { Route as QuizzesQuizIdRouteImport } from './routes/quizzes.$quizId'
import { Route as QuizzesNewRouteImport } from './routes/quizzes.new'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsBrandingRouteImport } from './routes/settings.branding'
import { Route as SettingsCommunityRouteImport } from './routes/settings.community'
import { Route as SettingsIntegrationsRouteImport } from './routes/settings.integrations'
import { Route as SettingsRulesRouteImport } from './routes/settings.rules'
import { Route as SettingsSecurityRouteImport } from './routes/settings.security'
import { Route as StoreIndexRouteImport } from './routes/store.index'
import { Route as StoreCouponsRouteImport } from './routes/store.coupons'
import { Route as StoreOrdersRouteImport } from './routes/store.orders'
import { Route as StoreRedemptionsRouteImport } from './routes/store.redemptions'
import { Route as SubscriptionsIndexRouteImport } from './routes/subscriptions.index'
import { Route as SubscriptionsAnalyticsRouteImport } from './routes/subscriptions.analytics'
import { Route as SubscriptionsSubscribersRouteImport } from './routes/subscriptions.subscribers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsRoute = CreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsRoute = CreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ModerationRoute = ModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsRoute = QuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesRoute = QuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsIndexRoute = AnalyticsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsReportsRoute = AnalyticsReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AnalyticsRoute,
} as any)
const CreatorsIndexRoute = CreatorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreatorsRoute,
} as any)
const CreatorsCreatorIdRoute = CreatorsCreatorIdRouteImport.update({
  id: '/$creatorId',
  path: '/$creatorId',
  getParentRoute: () => CreatorsRoute,
} as any)
const CreditsIndexRoute = CreditsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreditsRoute,
} as any)
const CreditsAdjustmentsRoute = CreditsAdjustmentsRouteImport.update({
  id: '/adjustments',
  path: '/adjustments',
  getParentRoute: () => CreditsRoute,
} as any)
const CreditsAnalyticsRoute = CreditsAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => CreditsRoute,
} as any)
const CreditsRulesRoute = CreditsRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => CreditsRoute,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LibraryRoute,
} as any)
const LibraryResourceIdRoute = LibraryResourceIdRouteImport.update({
  id: '/$resourceId',
  path: '/$resourceId',
  getParentRoute: () => LibraryRoute,
} as any)
const LibraryNewRoute = LibraryNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LibraryRoute,
} as any)
const ModerationIndexRoute = ModerationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModerationRoute,
} as any)
const ModerationCommunityRoute = ModerationCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => ModerationRoute,
} as any)
const ModerationCreatorsRoute = ModerationCreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => ModerationRoute,
} as any)
const ModerationQuizzesRoute = ModerationQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => ModerationRoute,
} as any)
const QuizzesIndexRoute = QuizzesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QuizzesRoute,
} as any)
const QuizzesQuizIdRoute = QuizzesQuizIdRouteImport.update({
  id: '/$quizId',
  path: '/$quizId',
  getParentRoute: () => QuizzesRoute,
} as any)
const QuizzesNewRoute = QuizzesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => QuizzesRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBrandingRoute = SettingsBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCommunityRoute = SettingsCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsRulesRoute = SettingsRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SettingsRoute,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCouponsRoute = StoreCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => StoreRoute,
} as any)
const StoreOrdersRoute = StoreOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => StoreRoute,
} as any)
const StoreRedemptionsRoute = StoreRedemptionsRouteImport.update({
  id: '/redemptions',
  path: '/redemptions',
  getParentRoute: () => StoreRoute,
} as any)
const SubscriptionsIndexRoute = SubscriptionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SubscriptionsRoute,
} as any)
const SubscriptionsAnalyticsRoute = SubscriptionsAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => SubscriptionsRoute,
} as any)
const SubscriptionsSubscribersRoute =
  SubscriptionsSubscribersRouteImport.update({
    id: '/subscribers',
    path: '/subscribers',
    getParentRoute: () => SubscriptionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/audit-logs': typeof AuditLogsRoute
  '/creators': typeof CreatorsRouteWithChildren
  '/credits': typeof CreditsRouteWithChildren
  '/library': typeof LibraryRouteWithChildren
  '/moderation': typeof ModerationRouteWithChildren
  '/monitoring': typeof MonitoringRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/questions': typeof QuestionsRoute
  '/quizzes': typeof QuizzesRouteWithChildren
  '/reports': typeof ReportsRoute
  '/rewards': typeof RewardsRoute
  '/roles': typeof RolesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/store': typeof StoreRouteWithChildren
  '/subscriptions': typeof SubscriptionsRouteWithChildren
  '/support': typeof SupportRoute
  '/users': typeof UsersRoute
  '/analytics/reports': typeof AnalyticsReportsRoute
  '/creators/$creatorId': typeof CreatorsCreatorIdRoute
  '/credits/adjustments': typeof CreditsAdjustmentsRoute
  '/credits/analytics': typeof CreditsAnalyticsRoute
  '/credits/rules': typeof CreditsRulesRoute
  '/library/$resourceId': typeof LibraryResourceIdRoute
  '/library/new': typeof LibraryNewRoute
  '/moderation/community': typeof ModerationCommunityRoute
  '/moderation/creators': typeof ModerationCreatorsRoute
  '/moderation/quizzes': typeof ModerationQuizzesRoute
  '/quizzes/$quizId': typeof QuizzesQuizIdRoute
  '/quizzes/new': typeof QuizzesNewRoute
  '/settings/branding': typeof SettingsBrandingRoute
  '/settings/community': typeof SettingsCommunityRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/rules': typeof SettingsRulesRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/store/coupons': typeof StoreCouponsRoute
  '/store/orders': typeof StoreOrdersRoute
  '/store/redemptions': typeof StoreRedemptionsRoute
  '/subscriptions/analytics': typeof SubscriptionsAnalyticsRoute
  '/subscriptions/subscribers': typeof SubscriptionsSubscribersRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/creators/': typeof CreatorsIndexRoute
  '/credits/': typeof CreditsIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/moderation/': typeof ModerationIndexRoute
  '/quizzes/': typeof QuizzesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/store/': typeof StoreIndexRoute
  '/subscriptions/': typeof SubscriptionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/monitoring': typeof MonitoringRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/questions': typeof QuestionsRoute
  '/reports': typeof ReportsRoute
  '/rewards': typeof RewardsRoute
  '/roles': typeof RolesRoute
  '/support': typeof SupportRoute
  '/users': typeof UsersRoute
  '/analytics/reports': typeof AnalyticsReportsRoute
  '/creators/$creatorId': typeof CreatorsCreatorIdRoute
  '/credits/adjustments': typeof CreditsAdjustmentsRoute
  '/credits/analytics': typeof CreditsAnalyticsRoute
  '/credits/rules': typeof CreditsRulesRoute
  '/library/$resourceId': typeof LibraryResourceIdRoute
  '/library/new': typeof LibraryNewRoute
  '/moderation/community': typeof ModerationCommunityRoute
  '/moderation/creators': typeof ModerationCreatorsRoute
  '/moderation/quizzes': typeof ModerationQuizzesRoute
  '/quizzes/$quizId': typeof QuizzesQuizIdRoute
  '/quizzes/new': typeof QuizzesNewRoute
  '/settings/branding': typeof SettingsBrandingRoute
  '/settings/community': typeof SettingsCommunityRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/rules': typeof SettingsRulesRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/store/coupons': typeof StoreCouponsRoute
  '/store/orders': typeof StoreOrdersRoute
  '/store/redemptions': typeof StoreRedemptionsRoute
  '/subscriptions/analytics': typeof SubscriptionsAnalyticsRoute
  '/subscriptions/subscribers': typeof SubscriptionsSubscribersRoute
  '/analytics': typeof AnalyticsIndexRoute
  '/creators': typeof CreatorsIndexRoute
  '/credits': typeof CreditsIndexRoute
  '/library': typeof LibraryIndexRoute
  '/moderation': typeof ModerationIndexRoute
  '/quizzes': typeof QuizzesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/store': typeof StoreIndexRoute
  '/subscriptions': typeof SubscriptionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/audit-logs': typeof AuditLogsRoute
  '/creators': typeof CreatorsRouteWithChildren
  '/credits': typeof CreditsRouteWithChildren
  '/library': typeof LibraryRouteWithChildren
  '/moderation': typeof ModerationRouteWithChildren
  '/monitoring': typeof MonitoringRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/questions': typeof QuestionsRoute
  '/quizzes': typeof QuizzesRouteWithChildren
  '/reports': typeof ReportsRoute
  '/rewards': typeof RewardsRoute
  '/roles': typeof RolesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/store': typeof StoreRouteWithChildren
  '/subscriptions': typeof SubscriptionsRouteWithChildren
  '/support': typeof SupportRoute
  '/users': typeof UsersRoute
  '/analytics/reports': typeof AnalyticsReportsRoute
  '/creators/$creatorId': typeof CreatorsCreatorIdRoute
  '/credits/adjustments': typeof CreditsAdjustmentsRoute
  '/credits/analytics': typeof CreditsAnalyticsRoute
  '/credits/rules': typeof CreditsRulesRoute
  '/library/$resourceId': typeof LibraryResourceIdRoute
  '/library/new': typeof LibraryNewRoute
  '/moderation/community': typeof ModerationCommunityRoute
  '/moderation/creators': typeof ModerationCreatorsRoute
  '/moderation/quizzes': typeof ModerationQuizzesRoute
  '/quizzes/$quizId': typeof QuizzesQuizIdRoute
  '/quizzes/new': typeof QuizzesNewRoute
  '/settings/branding': typeof SettingsBrandingRoute
  '/settings/community': typeof SettingsCommunityRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/rules': typeof SettingsRulesRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/store/coupons': typeof StoreCouponsRoute
  '/store/orders': typeof StoreOrdersRoute
  '/store/redemptions': typeof StoreRedemptionsRoute
  '/subscriptions/analytics': typeof SubscriptionsAnalyticsRoute
  '/subscriptions/subscribers': typeof SubscriptionsSubscribersRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/creators/': typeof CreatorsIndexRoute
  '/credits/': typeof CreditsIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/moderation/': typeof ModerationIndexRoute
  '/quizzes/': typeof QuizzesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/store/': typeof StoreIndexRoute
  '/subscriptions/': typeof SubscriptionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/analytics'
    | '/audit-logs'
    | '/creators'
    | '/credits'
    | '/library'
    | '/moderation'
    | '/monitoring'
    | '/notifications'
    | '/payments'
    | '/questions'
    | '/quizzes'
    | '/reports'
    | '/rewards'
    | '/roles'
    | '/settings'
    | '/store'
    | '/subscriptions'
    | '/support'
    | '/users'
    | '/analytics/reports'
    | '/creators/$creatorId'
    | '/credits/adjustments'
    | '/credits/analytics'
    | '/credits/rules'
    | '/library/$resourceId'
    | '/library/new'
    | '/moderation/community'
    | '/moderation/creators'
    | '/moderation/quizzes'
    | '/quizzes/$quizId'
    | '/quizzes/new'
    | '/settings/branding'
    | '/settings/community'
    | '/settings/integrations'
    | '/settings/rules'
    | '/settings/security'
    | '/store/coupons'
    | '/store/orders'
    | '/store/redemptions'
    | '/subscriptions/analytics'
    | '/subscriptions/subscribers'
    | '/analytics/'
    | '/creators/'
    | '/credits/'
    | '/library/'
    | '/moderation/'
    | '/quizzes/'
    | '/settings/'
    | '/store/'
    | '/subscriptions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/audit-logs'
    | '/monitoring'
    | '/notifications'
    | '/payments'
    | '/questions'
    | '/reports'
    | '/rewards'
    | '/roles'
    | '/support'
    | '/users'
    | '/analytics/reports'
    | '/creators/$creatorId'
    | '/credits/adjustments'
    | '/credits/analytics'
    | '/credits/rules'
    | '/library/$resourceId'
    | '/library/new'
    | '/moderation/community'
    | '/moderation/creators'
    | '/moderation/quizzes'
    | '/quizzes/$quizId'
    | '/quizzes/new'
    | '/settings/branding'
    | '/settings/community'
    | '/settings/integrations'
    | '/settings/rules'
    | '/settings/security'
    | '/store/coupons'
    | '/store/orders'
    | '/store/redemptions'
    | '/subscriptions/analytics'
    | '/subscriptions/subscribers'
    | '/analytics'
    | '/creators'
    | '/credits'
    | '/library'
    | '/moderation'
    | '/quizzes'
    | '/settings'
    | '/store'
    | '/subscriptions'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/analytics'
    | '/audit-logs'
    | '/creators'
    | '/credits'
    | '/library'
    | '/moderation'
    | '/monitoring'
    | '/notifications'
    | '/payments'
    | '/questions'
    | '/quizzes'
    | '/reports'
    | '/rewards'
    | '/roles'
    | '/settings'
    | '/store'
    | '/subscriptions'
    | '/support'
    | '/users'
    | '/analytics/reports'
    | '/creators/$creatorId'
    | '/credits/adjustments'
    | '/credits/analytics'
    | '/credits/rules'
    | '/library/$resourceId'
    | '/library/new'
    | '/moderation/community'
    | '/moderation/creators'
    | '/moderation/quizzes'
    | '/quizzes/$quizId'
    | '/quizzes/new'
    | '/settings/branding'
    | '/settings/community'
    | '/settings/integrations'
    | '/settings/rules'
    | '/settings/security'
    | '/store/coupons'
    | '/store/orders'
    | '/store/redemptions'
    | '/subscriptions/analytics'
    | '/subscriptions/subscribers'
    | '/analytics/'
    | '/creators/'
    | '/credits/'
    | '/library/'
    | '/moderation/'
    | '/quizzes/'
    | '/settings/'
    | '/store/'
    | '/subscriptions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  AnalyticsRoute: typeof AnalyticsRouteWithChildren
  AuditLogsRoute: typeof AuditLogsRoute
  CreatorsRoute: typeof CreatorsRouteWithChildren
  CreditsRoute: typeof CreditsRouteWithChildren
  LibraryRoute: typeof LibraryRouteWithChildren
  ModerationRoute: typeof ModerationRouteWithChildren
  MonitoringRoute: typeof MonitoringRoute
  NotificationsRoute: typeof NotificationsRoute
  PaymentsRoute: typeof PaymentsRoute
  QuestionsRoute: typeof QuestionsRoute
  QuizzesRoute: typeof QuizzesRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  RewardsRoute: typeof RewardsRoute
  RolesRoute: typeof RolesRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  StoreRoute: typeof StoreRouteWithChildren
  SubscriptionsRoute: typeof SubscriptionsRouteWithChildren
  SupportRoute: typeof SupportRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators': {
      id: '/creators'
      path: '/creators'
      fullPath: '/creators'
      preLoaderRoute: typeof CreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderation': {
      id: '/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof ModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions': {
      id: '/questions'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof QuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes': {
      id: '/quizzes'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof QuizzesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/': {
      id: '/analytics/'
      path: '/'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AnalyticsIndexRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/reports': {
      id: '/analytics/reports'
      path: '/reports'
      fullPath: '/analytics/reports'
      preLoaderRoute: typeof AnalyticsReportsRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/creators/': {
      id: '/creators/'
      path: '/'
      fullPath: '/creators/'
      preLoaderRoute: typeof CreatorsIndexRouteImport
      parentRoute: typeof CreatorsRoute
    }
    '/creators/$creatorId': {
      id: '/creators/$creatorId'
      path: '/$creatorId'
      fullPath: '/creators/$creatorId'
      preLoaderRoute: typeof CreatorsCreatorIdRouteImport
      parentRoute: typeof CreatorsRoute
    }
    '/credits/': {
      id: '/credits/'
      path: '/'
      fullPath: '/credits/'
      preLoaderRoute: typeof CreditsIndexRouteImport
      parentRoute: typeof CreditsRoute
    }
    '/credits/adjustments': {
      id: '/credits/adjustments'
      path: '/adjustments'
      fullPath: '/credits/adjustments'
      preLoaderRoute: typeof CreditsAdjustmentsRouteImport
      parentRoute: typeof CreditsRoute
    }
    '/credits/analytics': {
      id: '/credits/analytics'
      path: '/analytics'
      fullPath: '/credits/analytics'
      preLoaderRoute: typeof CreditsAnalyticsRouteImport
      parentRoute: typeof CreditsRoute
    }
    '/credits/rules': {
      id: '/credits/rules'
      path: '/rules'
      fullPath: '/credits/rules'
      preLoaderRoute: typeof CreditsRulesRouteImport
      parentRoute: typeof CreditsRoute
    }
    '/library/': {
      id: '/library/'
      path: '/'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/library/$resourceId': {
      id: '/library/$resourceId'
      path: '/$resourceId'
      fullPath: '/library/$resourceId'
      preLoaderRoute: typeof LibraryResourceIdRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/library/new': {
      id: '/library/new'
      path: '/new'
      fullPath: '/library/new'
      preLoaderRoute: typeof LibraryNewRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/moderation/': {
      id: '/moderation/'
      path: '/'
      fullPath: '/moderation/'
      preLoaderRoute: typeof ModerationIndexRouteImport
      parentRoute: typeof ModerationRoute
    }
    '/moderation/community': {
      id: '/moderation/community'
      path: '/community'
      fullPath: '/moderation/community'
      preLoaderRoute: typeof ModerationCommunityRouteImport
      parentRoute: typeof ModerationRoute
    }
    '/moderation/creators': {
      id: '/moderation/creators'
      path: '/creators'
      fullPath: '/moderation/creators'
      preLoaderRoute: typeof ModerationCreatorsRouteImport
      parentRoute: typeof ModerationRoute
    }
    '/moderation/quizzes': {
      id: '/moderation/quizzes'
      path: '/quizzes'
      fullPath: '/moderation/quizzes'
      preLoaderRoute: typeof ModerationQuizzesRouteImport
      parentRoute: typeof ModerationRoute
    }
    '/quizzes/': {
      id: '/quizzes/'
      path: '/'
      fullPath: '/quizzes/'
      preLoaderRoute: typeof QuizzesIndexRouteImport
      parentRoute: typeof QuizzesRoute
    }
    '/quizzes/$quizId': {
      id: '/quizzes/$quizId'
      path: '/$quizId'
      fullPath: '/quizzes/$quizId'
      preLoaderRoute: typeof QuizzesQuizIdRouteImport
      parentRoute: typeof QuizzesRoute
    }
    '/quizzes/new': {
      id: '/quizzes/new'
      path: '/new'
      fullPath: '/quizzes/new'
      preLoaderRoute: typeof QuizzesNewRouteImport
      parentRoute: typeof QuizzesRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/branding': {
      id: '/settings/branding'
      path: '/branding'
      fullPath: '/settings/branding'
      preLoaderRoute: typeof SettingsBrandingRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/community': {
      id: '/settings/community'
      path: '/community'
      fullPath: '/settings/community'
      preLoaderRoute: typeof SettingsCommunityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/integrations': {
      id: '/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/rules': {
      id: '/settings/rules'
      path: '/rules'
      fullPath: '/settings/rules'
      preLoaderRoute: typeof SettingsRulesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/store/': {
      id: '/store/'
      path: '/'
      fullPath: '/store/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/coupons': {
      id: '/store/coupons'
      path: '/coupons'
      fullPath: '/store/coupons'
      preLoaderRoute: typeof StoreCouponsRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/orders': {
      id: '/store/orders'
      path: '/orders'
      fullPath: '/store/orders'
      preLoaderRoute: typeof StoreOrdersRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/redemptions': {
      id: '/store/redemptions'
      path: '/redemptions'
      fullPath: '/store/redemptions'
      preLoaderRoute: typeof StoreRedemptionsRouteImport
      parentRoute: typeof StoreRoute
    }
    '/subscriptions/': {
      id: '/subscriptions/'
      path: '/'
      fullPath: '/subscriptions/'
      preLoaderRoute: typeof SubscriptionsIndexRouteImport
      parentRoute: typeof SubscriptionsRoute
    }
    '/subscriptions/analytics': {
      id: '/subscriptions/analytics'
      path: '/analytics'
      fullPath: '/subscriptions/analytics'
      preLoaderRoute: typeof SubscriptionsAnalyticsRouteImport
      parentRoute: typeof SubscriptionsRoute
    }
    '/subscriptions/subscribers': {
      id: '/subscriptions/subscribers'
      path: '/subscribers'
      fullPath: '/subscriptions/subscribers'
      preLoaderRoute: typeof SubscriptionsSubscribersRouteImport
      parentRoute: typeof SubscriptionsRoute
    }
  }
}

interface AnalyticsRouteChildren {
  AnalyticsReportsRoute: typeof AnalyticsReportsRoute
  AnalyticsIndexRoute: typeof AnalyticsIndexRoute
}

const AnalyticsRouteChildren: AnalyticsRouteChildren = {
  AnalyticsReportsRoute: AnalyticsReportsRoute,
  AnalyticsIndexRoute: AnalyticsIndexRoute,
}

const AnalyticsRouteWithChildren = AnalyticsRoute._addFileChildren(
  AnalyticsRouteChildren,
)

interface CreatorsRouteChildren {
  CreatorsCreatorIdRoute: typeof CreatorsCreatorIdRoute
  CreatorsIndexRoute: typeof CreatorsIndexRoute
}

const CreatorsRouteChildren: CreatorsRouteChildren = {
  CreatorsCreatorIdRoute: CreatorsCreatorIdRoute,
  CreatorsIndexRoute: CreatorsIndexRoute,
}

const CreatorsRouteWithChildren = CreatorsRoute._addFileChildren(
  CreatorsRouteChildren,
)

interface CreditsRouteChildren {
  CreditsAdjustmentsRoute: typeof CreditsAdjustmentsRoute
  CreditsAnalyticsRoute: typeof CreditsAnalyticsRoute
  CreditsRulesRoute: typeof CreditsRulesRoute
  CreditsIndexRoute: typeof CreditsIndexRoute
}

const CreditsRouteChildren: CreditsRouteChildren = {
  CreditsAdjustmentsRoute: CreditsAdjustmentsRoute,
  CreditsAnalyticsRoute: CreditsAnalyticsRoute,
  CreditsRulesRoute: CreditsRulesRoute,
  CreditsIndexRoute: CreditsIndexRoute,
}

const CreditsRouteWithChildren =
  CreditsRoute._addFileChildren(CreditsRouteChildren)

interface LibraryRouteChildren {
  LibraryResourceIdRoute: typeof LibraryResourceIdRoute
  LibraryNewRoute: typeof LibraryNewRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
}

const LibraryRouteChildren: LibraryRouteChildren = {
  LibraryResourceIdRoute: LibraryResourceIdRoute,
  LibraryNewRoute: LibraryNewRoute,
  LibraryIndexRoute: LibraryIndexRoute,
}

const LibraryRouteWithChildren =
  LibraryRoute._addFileChildren(LibraryRouteChildren)

interface ModerationRouteChildren {
  ModerationCommunityRoute: typeof ModerationCommunityRoute
  ModerationCreatorsRoute: typeof ModerationCreatorsRoute
  ModerationQuizzesRoute: typeof ModerationQuizzesRoute
  ModerationIndexRoute: typeof ModerationIndexRoute
}

const ModerationRouteChildren: ModerationRouteChildren = {
  ModerationCommunityRoute: ModerationCommunityRoute,
  ModerationCreatorsRoute: ModerationCreatorsRoute,
  ModerationQuizzesRoute: ModerationQuizzesRoute,
  ModerationIndexRoute: ModerationIndexRoute,
}

const ModerationRouteWithChildren = ModerationRoute._addFileChildren(
  ModerationRouteChildren,
)

interface QuizzesRouteChildren {
  QuizzesQuizIdRoute: typeof QuizzesQuizIdRoute
  QuizzesNewRoute: typeof QuizzesNewRoute
  QuizzesIndexRoute: typeof QuizzesIndexRoute
}

const QuizzesRouteChildren: QuizzesRouteChildren = {
  QuizzesQuizIdRoute: QuizzesQuizIdRoute,
  QuizzesNewRoute: QuizzesNewRoute,
  QuizzesIndexRoute: QuizzesIndexRoute,
}

const QuizzesRouteWithChildren =
  QuizzesRoute._addFileChildren(QuizzesRouteChildren)

interface SettingsRouteChildren {
  SettingsBrandingRoute: typeof SettingsBrandingRoute
  SettingsCommunityRoute: typeof SettingsCommunityRoute
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsRulesRoute: typeof SettingsRulesRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsBrandingRoute: SettingsBrandingRoute,
  SettingsCommunityRoute: SettingsCommunityRoute,
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsRulesRoute: SettingsRulesRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface StoreRouteChildren {
  StoreCouponsRoute: typeof StoreCouponsRoute
  StoreOrdersRoute: typeof StoreOrdersRoute
  StoreRedemptionsRoute: typeof StoreRedemptionsRoute
  StoreIndexRoute: typeof StoreIndexRoute
}

const StoreRouteChildren: StoreRouteChildren = {
  StoreCouponsRoute: StoreCouponsRoute,
  StoreOrdersRoute: StoreOrdersRoute,
  StoreRedemptionsRoute: StoreRedemptionsRoute,
  StoreIndexRoute: StoreIndexRoute,
}

const StoreRouteWithChildren = StoreRoute._addFileChildren(StoreRouteChildren)

interface SubscriptionsRouteChildren {
  SubscriptionsAnalyticsRoute: typeof SubscriptionsAnalyticsRoute
  SubscriptionsSubscribersRoute: typeof SubscriptionsSubscribersRoute
  SubscriptionsIndexRoute: typeof SubscriptionsIndexRoute
}

const SubscriptionsRouteChildren: SubscriptionsRouteChildren = {
  SubscriptionsAnalyticsRoute: SubscriptionsAnalyticsRoute,
  SubscriptionsSubscribersRoute: SubscriptionsSubscribersRoute,
  SubscriptionsIndexRoute: SubscriptionsIndexRoute,
}

const SubscriptionsRouteWithChildren = SubscriptionsRoute._addFileChildren(
  SubscriptionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  AnalyticsRoute: AnalyticsRouteWithChildren,
  AuditLogsRoute: AuditLogsRoute,
  CreatorsRoute: CreatorsRouteWithChildren,
  CreditsRoute: CreditsRouteWithChildren,
  LibraryRoute: LibraryRouteWithChildren,
  ModerationRoute: ModerationRouteWithChildren,
  MonitoringRoute: MonitoringRoute,
  NotificationsRoute: NotificationsRoute,
  PaymentsRoute: PaymentsRoute,
  QuestionsRoute: QuestionsRoute,
  QuizzesRoute: QuizzesRouteWithChildren,
  ReportsRoute: ReportsRoute,
  RewardsRoute: RewardsRoute,
  RolesRoute: RolesRoute,
  SettingsRoute: SettingsRouteWithChildren,
  StoreRoute: StoreRouteWithChildren,
  SubscriptionsRoute: SubscriptionsRouteWithChildren,
  SupportRoute: SupportRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
