/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R404RouteImport } from './routes/404'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as GeolibraryRouteImport } from './routes/geolibrary'
import { Route as GeostoreRouteImport } from './routes/geostore'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlayRouteImport } from './routes/play'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as StoreRouteImport } from './routes/store'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AppAchievementsRouteImport } from './routes/_app.achievements'
import { Route as AppBillingRouteImport } from './routes/_app.billing'
import { Route as AppBookmarksRouteImport } from './routes/_app.bookmarks'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppProgressRouteImport } from './routes/_app.progress'
import { Route as AppQuizHistoryRouteImport } from './routes/_app.quiz-history'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AuthAgeVerificationRouteImport } from './routes/auth.age-verification'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthOnboardingRouteImport } from './routes/auth.onboarding'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth.verify-email'
import { Route as CommunityIndexRouteImport } from './routes/community.index'
import { Route as CommunityChallengesRouteImport } from './routes/community.challenges'
import { Route as CommunityDiscoverRouteImport } from './routes/community.discover'
import { Route as CommunityEventsRouteImport } from './routes/community.events'
import { Route as CommunityFeedRouteImport } from './routes/community.feed'
import { Route as CommunityFriendsRouteImport } from './routes/community.friends'
import { Route as CommunityMembersRouteImport } from './routes/community.members'
import { Route as CommunityNotificationsRouteImport } from './routes/community.notifications'
import { Route as CommunitySavedRouteImport } from './routes/community.saved'
import { Route as CommunityTopicsRouteImport } from './routes/community.topics'
import { Route as GeolibraryIndexRouteImport } from './routes/geolibrary.index'
import { Route as GeolibraryBookmarksRouteImport } from './routes/geolibrary.bookmarks'
import { Route as GeolibraryBrowseRouteImport } from './routes/geolibrary.browse'
import { Route as GeolibraryProgressRouteImport } from './routes/geolibrary.progress'
import { Route as GeostoreIndexRouteImport } from './routes/geostore.index'
import { Route as GeostoreBrowseRouteImport } from './routes/geostore.browse'
import { Route as GeostoreCartRouteImport } from './routes/geostore.cart'
import { Route as GeostoreCheckoutRouteImport } from './routes/geostore.checkout'
import { Route as GeostoreOffersRouteImport } from './routes/geostore.offers'
import { Route as GeostoreOrdersRouteImport } from './routes/geostore.orders'
import { Route as GeostoreRewardsRouteImport } from './routes/geostore.rewards'
import { Route as GeostoreWishlistRouteImport } from './routes/geostore.wishlist'
import { Route as PlayIndexRouteImport } from './routes/play.index'
import { Route as PlayCreditHistoryRouteImport } from './routes/play.credit-history'
import { Route as PlayDailyChallengesRouteImport } from './routes/play.daily-challenges'
import { Route as PlayEventsRouteImport } from './routes/play.events'
import { Route as PlayLeaderboardRouteImport } from './routes/play.leaderboard'
import { Route as PlayLevelSystemRouteImport } from './routes/play.level-system'
import { Route as PlayLobbyRouteImport } from './routes/play.lobby'
import { Route as PlayMatchmakingRouteImport } from './routes/play.matchmaking'
import { Route as PlayModesRouteImport } from './routes/play.modes'
import { Route as PlayProgressionRouteImport } from './routes/play.progression'
import { Route as PlayQuizRouteImport } from './routes/play.quiz'
import { Route as PlayRewardsRouteImport } from './routes/play.rewards'
import { Route as PlaySearchRouteImport } from './routes/play.search'
import { Route as PlayStreakRouteImport } from './routes/play.streak'
import { Route as PlayWeeklyChallengesRouteImport } from './routes/play.weekly-challenges'
import { Route as PricingIndexRouteImport } from './routes/pricing.index'
import { Route as PricingCompareRouteImport } from './routes/pricing.compare'
import { Route as StudioIndexRouteImport } from './routes/studio.index'
import { Route as StudioAnalyticsRouteImport } from './routes/studio.analytics'
import { Route as StudioAudienceRouteImport } from './routes/studio.audience'
import { Route as StudioEarningsRouteImport } from './routes/studio.earnings'
import { Route as StudioMediaRouteImport } from './routes/studio.media'
import { Route as StudioSettingsRouteImport } from './routes/studio.settings'
import { Route as AppProfileIndexRouteImport } from './routes/_app.profile.index'
import { Route as AppProfileEditRouteImport } from './routes/_app.profile.edit'
import { Route as CommunityMemberHandleRouteImport } from './routes/community.member.$handle'
import { Route as CommunityPostPostIdRouteImport } from './routes/community.post.$postId'
import { Route as CommunityTopicSlugRouteImport } from './routes/community.topic.$slug'
import { Route as GeolibraryArticleSlugRouteImport } from './routes/geolibrary.article.$slug'
import { Route as GeolibraryCollectionsIndexRouteImport } from './routes/geolibrary.collections.index'
import { Route as GeolibraryCollectionsSlugRouteImport } from './routes/geolibrary.collections.$slug'
import { Route as GeolibraryCreatorsIndexRouteImport } from './routes/geolibrary.creators.index'
import { Route as GeolibraryCreatorsHandleRouteImport } from './routes/geolibrary.creators.$handle'
import { Route as GeostoreCategorySlugRouteImport } from './routes/geostore.category.$slug'
import { Route as GeostoreProductSlugRouteImport } from './routes/geostore.product.$slug'
import { Route as PlayCollectionsIndexRouteImport } from './routes/play.collections.index'
import { Route as PlayCollectionsSlugRouteImport } from './routes/play.collections.$slug'
import { Route as PlayHistoryIndexRouteImport } from './routes/play.history.index'
import { Route as PlayHistoryMatchIdRouteImport } from './routes/play.history.$matchId'
import { Route as PlayQuizIndexRouteImport } from './routes/play.quiz.index'
import { Route as PlayQuizMultiplayerRouteImport } from './routes/play.quiz.multiplayer'
import { Route as PlayQuizPvpRouteImport } from './routes/play.quiz.pvp'
import { Route as PlayQuizResultRouteImport } from './routes/play.quiz.result'
import { Route as PlayQuizReviewRouteImport } from './routes/play.quiz.review'
import { Route as PlayQuizSoloRouteImport } from './routes/play.quiz.solo'
import { Route as PlayTournamentsIndexRouteImport } from './routes/play.tournaments.index'
import { Route as PlayTournamentsSlugRouteImport } from './routes/play.tournaments.$slug'
import { Route as StudioArticlesIndexRouteImport } from './routes/studio.articles.index'
import { Route as StudioArticlesArticleIdRouteImport } from './routes/studio.articles.$articleId'
import { Route as StudioArticlesNewRouteImport } from './routes/studio.articles.new'
import { Route as StudioQuizzesIndexRouteImport } from './routes/studio.quizzes.index'
import { Route as StudioQuizzesQuizIdRouteImport } from './routes/studio.quizzes.$quizId'
import { Route as StudioQuizzesNewRouteImport } from './routes/studio.quizzes.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GeolibraryRoute = GeolibraryRouteImport.update({
  id: '/geolibrary',
  path: '/geolibrary',
  getParentRoute: () => rootRouteImport,
} as any)
const GeostoreRoute = GeostoreRouteImport.update({
  id: '/geostore',
  path: '/geostore',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAchievementsRoute = AppAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppBookmarksRoute = AppBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizHistoryRoute = AppQuizHistoryRouteImport.update({
  id: '/quiz-history',
  path: '/quiz-history',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AuthAgeVerificationRoute = AuthAgeVerificationRouteImport.update({
  id: '/auth/age-verification',
  path: '/auth/age-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOnboardingRoute = AuthOnboardingRouteImport.update({
  id: '/auth/onboarding',
  path: '/auth/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CommunityRoute,
} as any)
const CommunityChallengesRoute = CommunityChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => CommunityRoute,
} as any)
const CommunityDiscoverRoute = CommunityDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => CommunityRoute,
} as any)
const CommunityEventsRoute = CommunityEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => CommunityRoute,
} as any)
const CommunityFeedRoute = CommunityFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => CommunityRoute,
} as any)
const CommunityFriendsRoute = CommunityFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => CommunityRoute,
} as any)
const CommunityMembersRoute = CommunityMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => CommunityRoute,
} as any)
const CommunityNotificationsRoute = CommunityNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => CommunityRoute,
} as any)
const CommunitySavedRoute = CommunitySavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => CommunityRoute,
} as any)
const CommunityTopicsRoute = CommunityTopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => CommunityRoute,
} as any)
const GeolibraryIndexRoute = GeolibraryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GeolibraryRoute,
} as any)
const GeolibraryBookmarksRoute = GeolibraryBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => GeolibraryRoute,
} as any)
const GeolibraryBrowseRoute = GeolibraryBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => GeolibraryRoute,
} as any)
const GeolibraryProgressRoute = GeolibraryProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => GeolibraryRoute,
} as any)
const GeostoreIndexRoute = GeostoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GeostoreRoute,
} as any)
const GeostoreBrowseRoute = GeostoreBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => GeostoreRoute,
} as any)
const GeostoreCartRoute = GeostoreCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => GeostoreRoute,
} as any)
const GeostoreCheckoutRoute = GeostoreCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => GeostoreRoute,
} as any)
const GeostoreOffersRoute = GeostoreOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => GeostoreRoute,
} as any)
const GeostoreOrdersRoute = GeostoreOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => GeostoreRoute,
} as any)
const GeostoreRewardsRoute = GeostoreRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => GeostoreRoute,
} as any)
const GeostoreWishlistRoute = GeostoreWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => GeostoreRoute,
} as any)
const PlayIndexRoute = PlayIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlayRoute,
} as any)
const PlayCreditHistoryRoute = PlayCreditHistoryRouteImport.update({
  id: '/credit-history',
  path: '/credit-history',
  getParentRoute: () => PlayRoute,
} as any)
const PlayDailyChallengesRoute = PlayDailyChallengesRouteImport.update({
  id: '/daily-challenges',
  path: '/daily-challenges',
  getParentRoute: () => PlayRoute,
} as any)
const PlayEventsRoute = PlayEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => PlayRoute,
} as any)
const PlayLeaderboardRoute = PlayLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => PlayRoute,
} as any)
const PlayLevelSystemRoute = PlayLevelSystemRouteImport.update({
  id: '/level-system',
  path: '/level-system',
  getParentRoute: () => PlayRoute,
} as any)
const PlayLobbyRoute = PlayLobbyRouteImport.update({
  id: '/lobby',
  path: '/lobby',
  getParentRoute: () => PlayRoute,
} as any)
const PlayMatchmakingRoute = PlayMatchmakingRouteImport.update({
  id: '/matchmaking',
  path: '/matchmaking',
  getParentRoute: () => PlayRoute,
} as any)
const PlayModesRoute = PlayModesRouteImport.update({
  id: '/modes',
  path: '/modes',
  getParentRoute: () => PlayRoute,
} as any)
const PlayProgressionRoute = PlayProgressionRouteImport.update({
  id: '/progression',
  path: '/progression',
  getParentRoute: () => PlayRoute,
} as any)
const PlayQuizRoute = PlayQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => PlayRoute,
} as any)
const PlayRewardsRoute = PlayRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => PlayRoute,
} as any)
const PlaySearchRoute = PlaySearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => PlayRoute,
} as any)
const PlayStreakRoute = PlayStreakRouteImport.update({
  id: '/streak',
  path: '/streak',
  getParentRoute: () => PlayRoute,
} as any)
const PlayWeeklyChallengesRoute = PlayWeeklyChallengesRouteImport.update({
  id: '/weekly-challenges',
  path: '/weekly-challenges',
  getParentRoute: () => PlayRoute,
} as any)
const PricingIndexRoute = PricingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PricingRoute,
} as any)
const PricingCompareRoute = PricingCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => PricingRoute,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioAnalyticsRoute = StudioAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => StudioRoute,
} as any)
const StudioAudienceRoute = StudioAudienceRouteImport.update({
  id: '/audience',
  path: '/audience',
  getParentRoute: () => StudioRoute,
} as any)
const StudioEarningsRoute = StudioEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => StudioRoute,
} as any)
const StudioMediaRoute = StudioMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => StudioRoute,
} as any)
const StudioSettingsRoute = StudioSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StudioRoute,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProfileRoute,
} as any)
const AppProfileEditRoute = AppProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppProfileRoute,
} as any)
const CommunityMemberHandleRoute = CommunityMemberHandleRouteImport.update({
  id: '/member/$handle',
  path: '/member/$handle',
  getParentRoute: () => CommunityRoute,
} as any)
const CommunityPostPostIdRoute = CommunityPostPostIdRouteImport.update({
  id: '/post/$postId',
  path: '/post/$postId',
  getParentRoute: () => CommunityRoute,
} as any)
const CommunityTopicSlugRoute = CommunityTopicSlugRouteImport.update({
  id: '/topic/$slug',
  path: '/topic/$slug',
  getParentRoute: () => CommunityRoute,
} as any)
const GeolibraryArticleSlugRoute = GeolibraryArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => GeolibraryRoute,
} as any)
const GeolibraryCollectionsIndexRoute =
  GeolibraryCollectionsIndexRouteImport.update({
    id: '/collections/',
    path: '/collections/',
    getParentRoute: () => GeolibraryRoute,
  } as any)
const GeolibraryCollectionsSlugRoute =
  GeolibraryCollectionsSlugRouteImport.update({
    id: '/collections/$slug',
    path: '/collections/$slug',
    getParentRoute: () => GeolibraryRoute,
  } as any)
const GeolibraryCreatorsIndexRoute = GeolibraryCreatorsIndexRouteImport.update({
  id: '/creators/',
  path: '/creators/',
  getParentRoute: () => GeolibraryRoute,
} as any)
const GeolibraryCreatorsHandleRoute =
  GeolibraryCreatorsHandleRouteImport.update({
    id: '/creators/$handle',
    path: '/creators/$handle',
    getParentRoute: () => GeolibraryRoute,
  } as any)
const GeostoreCategorySlugRoute = GeostoreCategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => GeostoreRoute,
} as any)
const GeostoreProductSlugRoute = GeostoreProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => GeostoreRoute,
} as any)
const PlayCollectionsIndexRoute = PlayCollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => PlayRoute,
} as any)
const PlayCollectionsSlugRoute = PlayCollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => PlayRoute,
} as any)
const PlayHistoryIndexRoute = PlayHistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => PlayRoute,
} as any)
const PlayHistoryMatchIdRoute = PlayHistoryMatchIdRouteImport.update({
  id: '/history/$matchId',
  path: '/history/$matchId',
  getParentRoute: () => PlayRoute,
} as any)
const PlayQuizIndexRoute = PlayQuizIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlayQuizRoute,
} as any)
const PlayQuizMultiplayerRoute = PlayQuizMultiplayerRouteImport.update({
  id: '/multiplayer',
  path: '/multiplayer',
  getParentRoute: () => PlayQuizRoute,
} as any)
const PlayQuizPvpRoute = PlayQuizPvpRouteImport.update({
  id: '/pvp',
  path: '/pvp',
  getParentRoute: () => PlayQuizRoute,
} as any)
const PlayQuizResultRoute = PlayQuizResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => PlayQuizRoute,
} as any)
const PlayQuizReviewRoute = PlayQuizReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => PlayQuizRoute,
} as any)
const PlayQuizSoloRoute = PlayQuizSoloRouteImport.update({
  id: '/solo',
  path: '/solo',
  getParentRoute: () => PlayQuizRoute,
} as any)
const PlayTournamentsIndexRoute = PlayTournamentsIndexRouteImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => PlayRoute,
} as any)
const PlayTournamentsSlugRoute = PlayTournamentsSlugRouteImport.update({
  id: '/tournaments/$slug',
  path: '/tournaments/$slug',
  getParentRoute: () => PlayRoute,
} as any)
const StudioArticlesIndexRoute = StudioArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioArticlesArticleIdRoute = StudioArticlesArticleIdRouteImport.update({
  id: '/articles/$articleId',
  path: '/articles/$articleId',
  getParentRoute: () => StudioRoute,
} as any)
const StudioArticlesNewRoute = StudioArticlesNewRouteImport.update({
  id: '/articles/new',
  path: '/articles/new',
  getParentRoute: () => StudioRoute,
} as any)
const StudioQuizzesIndexRoute = StudioQuizzesIndexRouteImport.update({
  id: '/quizzes/',
  path: '/quizzes/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioQuizzesQuizIdRoute = StudioQuizzesQuizIdRouteImport.update({
  id: '/quizzes/$quizId',
  path: '/quizzes/$quizId',
  getParentRoute: () => StudioRoute,
} as any)
const StudioQuizzesNewRoute = StudioQuizzesNewRouteImport.update({
  id: '/quizzes/new',
  path: '/quizzes/new',
  getParentRoute: () => StudioRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/community': typeof CommunityRouteWithChildren
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/geolibrary': typeof GeolibraryRouteWithChildren
  '/geostore': typeof GeostoreRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/play': typeof PlayRouteWithChildren
  '/pricing': typeof PricingRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/store': typeof StoreRoute
  '/studio': typeof StudioRouteWithChildren
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/achievements': typeof AppAchievementsRoute
  '/billing': typeof AppBillingRoute
  '/bookmarks': typeof AppBookmarksRoute
  '/dashboard': typeof AppDashboardRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRouteWithChildren
  '/progress': typeof AppProgressRoute
  '/quiz-history': typeof AppQuizHistoryRoute
  '/settings': typeof AppSettingsRoute
  '/auth/age-verification': typeof AuthAgeVerificationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/community/challenges': typeof CommunityChallengesRoute
  '/community/discover': typeof CommunityDiscoverRoute
  '/community/events': typeof CommunityEventsRoute
  '/community/feed': typeof CommunityFeedRoute
  '/community/friends': typeof CommunityFriendsRoute
  '/community/members': typeof CommunityMembersRoute
  '/community/notifications': typeof CommunityNotificationsRoute
  '/community/saved': typeof CommunitySavedRoute
  '/community/topics': typeof CommunityTopicsRoute
  '/geolibrary/bookmarks': typeof GeolibraryBookmarksRoute
  '/geolibrary/browse': typeof GeolibraryBrowseRoute
  '/geolibrary/progress': typeof GeolibraryProgressRoute
  '/geostore/browse': typeof GeostoreBrowseRoute
  '/geostore/cart': typeof GeostoreCartRoute
  '/geostore/checkout': typeof GeostoreCheckoutRoute
  '/geostore/offers': typeof GeostoreOffersRoute
  '/geostore/orders': typeof GeostoreOrdersRoute
  '/geostore/rewards': typeof GeostoreRewardsRoute
  '/geostore/wishlist': typeof GeostoreWishlistRoute
  '/play/credit-history': typeof PlayCreditHistoryRoute
  '/play/daily-challenges': typeof PlayDailyChallengesRoute
  '/play/events': typeof PlayEventsRoute
  '/play/leaderboard': typeof PlayLeaderboardRoute
  '/play/level-system': typeof PlayLevelSystemRoute
  '/play/lobby': typeof PlayLobbyRoute
  '/play/matchmaking': typeof PlayMatchmakingRoute
  '/play/modes': typeof PlayModesRoute
  '/play/progression': typeof PlayProgressionRoute
  '/play/quiz': typeof PlayQuizRouteWithChildren
  '/play/rewards': typeof PlayRewardsRoute
  '/play/search': typeof PlaySearchRoute
  '/play/streak': typeof PlayStreakRoute
  '/play/weekly-challenges': typeof PlayWeeklyChallengesRoute
  '/pricing/compare': typeof PricingCompareRoute
  '/studio/analytics': typeof StudioAnalyticsRoute
  '/studio/audience': typeof StudioAudienceRoute
  '/studio/earnings': typeof StudioEarningsRoute
  '/studio/media': typeof StudioMediaRoute
  '/studio/settings': typeof StudioSettingsRoute
  '/community/': typeof CommunityIndexRoute
  '/geolibrary/': typeof GeolibraryIndexRoute
  '/geostore/': typeof GeostoreIndexRoute
  '/play/': typeof PlayIndexRoute
  '/pricing/': typeof PricingIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/profile/edit': typeof AppProfileEditRoute
  '/community/member/$handle': typeof CommunityMemberHandleRoute
  '/community/post/$postId': typeof CommunityPostPostIdRoute
  '/community/topic/$slug': typeof CommunityTopicSlugRoute
  '/geolibrary/article/$slug': typeof GeolibraryArticleSlugRoute
  '/geolibrary/collections/$slug': typeof GeolibraryCollectionsSlugRoute
  '/geolibrary/creators/$handle': typeof GeolibraryCreatorsHandleRoute
  '/geostore/category/$slug': typeof GeostoreCategorySlugRoute
  '/geostore/product/$slug': typeof GeostoreProductSlugRoute
  '/play/collections/$slug': typeof PlayCollectionsSlugRoute
  '/play/history/$matchId': typeof PlayHistoryMatchIdRoute
  '/play/quiz/multiplayer': typeof PlayQuizMultiplayerRoute
  '/play/quiz/pvp': typeof PlayQuizPvpRoute
  '/play/quiz/result': typeof PlayQuizResultRoute
  '/play/quiz/review': typeof PlayQuizReviewRoute
  '/play/quiz/solo': typeof PlayQuizSoloRoute
  '/play/tournaments/$slug': typeof PlayTournamentsSlugRoute
  '/studio/articles/$articleId': typeof StudioArticlesArticleIdRoute
  '/studio/articles/new': typeof StudioArticlesNewRoute
  '/studio/quizzes/$quizId': typeof StudioQuizzesQuizIdRoute
  '/studio/quizzes/new': typeof StudioQuizzesNewRoute
  '/profile/': typeof AppProfileIndexRoute
  '/geolibrary/collections/': typeof GeolibraryCollectionsIndexRoute
  '/geolibrary/creators/': typeof GeolibraryCreatorsIndexRoute
  '/play/collections/': typeof PlayCollectionsIndexRoute
  '/play/history/': typeof PlayHistoryIndexRoute
  '/play/quiz/': typeof PlayQuizIndexRoute
  '/play/tournaments/': typeof PlayTournamentsIndexRoute
  '/studio/articles/': typeof StudioArticlesIndexRoute
  '/studio/quizzes/': typeof StudioQuizzesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/leaderboard': typeof LeaderboardRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/store': typeof StoreRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/achievements': typeof AppAchievementsRoute
  '/billing': typeof AppBillingRoute
  '/bookmarks': typeof AppBookmarksRoute
  '/dashboard': typeof AppDashboardRoute
  '/notifications': typeof AppNotificationsRoute
  '/progress': typeof AppProgressRoute
  '/quiz-history': typeof AppQuizHistoryRoute
  '/settings': typeof AppSettingsRoute
  '/auth/age-verification': typeof AuthAgeVerificationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/community/challenges': typeof CommunityChallengesRoute
  '/community/discover': typeof CommunityDiscoverRoute
  '/community/events': typeof CommunityEventsRoute
  '/community/feed': typeof CommunityFeedRoute
  '/community/friends': typeof CommunityFriendsRoute
  '/community/members': typeof CommunityMembersRoute
  '/community/notifications': typeof CommunityNotificationsRoute
  '/community/saved': typeof CommunitySavedRoute
  '/community/topics': typeof CommunityTopicsRoute
  '/geolibrary/bookmarks': typeof GeolibraryBookmarksRoute
  '/geolibrary/browse': typeof GeolibraryBrowseRoute
  '/geolibrary/progress': typeof GeolibraryProgressRoute
  '/geostore/browse': typeof GeostoreBrowseRoute
  '/geostore/cart': typeof GeostoreCartRoute
  '/geostore/checkout': typeof GeostoreCheckoutRoute
  '/geostore/offers': typeof GeostoreOffersRoute
  '/geostore/orders': typeof GeostoreOrdersRoute
  '/geostore/rewards': typeof GeostoreRewardsRoute
  '/geostore/wishlist': typeof GeostoreWishlistRoute
  '/play/credit-history': typeof PlayCreditHistoryRoute
  '/play/daily-challenges': typeof PlayDailyChallengesRoute
  '/play/events': typeof PlayEventsRoute
  '/play/leaderboard': typeof PlayLeaderboardRoute
  '/play/level-system': typeof PlayLevelSystemRoute
  '/play/lobby': typeof PlayLobbyRoute
  '/play/matchmaking': typeof PlayMatchmakingRoute
  '/play/modes': typeof PlayModesRoute
  '/play/progression': typeof PlayProgressionRoute
  '/play/rewards': typeof PlayRewardsRoute
  '/play/search': typeof PlaySearchRoute
  '/play/streak': typeof PlayStreakRoute
  '/play/weekly-challenges': typeof PlayWeeklyChallengesRoute
  '/pricing/compare': typeof PricingCompareRoute
  '/studio/analytics': typeof StudioAnalyticsRoute
  '/studio/audience': typeof StudioAudienceRoute
  '/studio/earnings': typeof StudioEarningsRoute
  '/studio/media': typeof StudioMediaRoute
  '/studio/settings': typeof StudioSettingsRoute
  '/community': typeof CommunityIndexRoute
  '/geolibrary': typeof GeolibraryIndexRoute
  '/geostore': typeof GeostoreIndexRoute
  '/play': typeof PlayIndexRoute
  '/pricing': typeof PricingIndexRoute
  '/studio': typeof StudioIndexRoute
  '/profile/edit': typeof AppProfileEditRoute
  '/community/member/$handle': typeof CommunityMemberHandleRoute
  '/community/post/$postId': typeof CommunityPostPostIdRoute
  '/community/topic/$slug': typeof CommunityTopicSlugRoute
  '/geolibrary/article/$slug': typeof GeolibraryArticleSlugRoute
  '/geolibrary/collections/$slug': typeof GeolibraryCollectionsSlugRoute
  '/geolibrary/creators/$handle': typeof GeolibraryCreatorsHandleRoute
  '/geostore/category/$slug': typeof GeostoreCategorySlugRoute
  '/geostore/product/$slug': typeof GeostoreProductSlugRoute
  '/play/collections/$slug': typeof PlayCollectionsSlugRoute
  '/play/history/$matchId': typeof PlayHistoryMatchIdRoute
  '/play/quiz/multiplayer': typeof PlayQuizMultiplayerRoute
  '/play/quiz/pvp': typeof PlayQuizPvpRoute
  '/play/quiz/result': typeof PlayQuizResultRoute
  '/play/quiz/review': typeof PlayQuizReviewRoute
  '/play/quiz/solo': typeof PlayQuizSoloRoute
  '/play/tournaments/$slug': typeof PlayTournamentsSlugRoute
  '/studio/articles/$articleId': typeof StudioArticlesArticleIdRoute
  '/studio/articles/new': typeof StudioArticlesNewRoute
  '/studio/quizzes/$quizId': typeof StudioQuizzesQuizIdRoute
  '/studio/quizzes/new': typeof StudioQuizzesNewRoute
  '/profile': typeof AppProfileIndexRoute
  '/geolibrary/collections': typeof GeolibraryCollectionsIndexRoute
  '/geolibrary/creators': typeof GeolibraryCreatorsIndexRoute
  '/play/collections': typeof PlayCollectionsIndexRoute
  '/play/history': typeof PlayHistoryIndexRoute
  '/play/quiz': typeof PlayQuizIndexRoute
  '/play/tournaments': typeof PlayTournamentsIndexRoute
  '/studio/articles': typeof StudioArticlesIndexRoute
  '/studio/quizzes': typeof StudioQuizzesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/_app': typeof AppRouteWithChildren
  '/about': typeof AboutRoute
  '/community': typeof CommunityRouteWithChildren
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/geolibrary': typeof GeolibraryRouteWithChildren
  '/geostore': typeof GeostoreRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/play': typeof PlayRouteWithChildren
  '/pricing': typeof PricingRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/store': typeof StoreRoute
  '/studio': typeof StudioRouteWithChildren
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/_app/achievements': typeof AppAchievementsRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/bookmarks': typeof AppBookmarksRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/profile': typeof AppProfileRouteWithChildren
  '/_app/progress': typeof AppProgressRoute
  '/_app/quiz-history': typeof AppQuizHistoryRoute
  '/_app/settings': typeof AppSettingsRoute
  '/auth/age-verification': typeof AuthAgeVerificationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/onboarding': typeof AuthOnboardingRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/community/challenges': typeof CommunityChallengesRoute
  '/community/discover': typeof CommunityDiscoverRoute
  '/community/events': typeof CommunityEventsRoute
  '/community/feed': typeof CommunityFeedRoute
  '/community/friends': typeof CommunityFriendsRoute
  '/community/members': typeof CommunityMembersRoute
  '/community/notifications': typeof CommunityNotificationsRoute
  '/community/saved': typeof CommunitySavedRoute
  '/community/topics': typeof CommunityTopicsRoute
  '/geolibrary/bookmarks': typeof GeolibraryBookmarksRoute
  '/geolibrary/browse': typeof GeolibraryBrowseRoute
  '/geolibrary/progress': typeof GeolibraryProgressRoute
  '/geostore/browse': typeof GeostoreBrowseRoute
  '/geostore/cart': typeof GeostoreCartRoute
  '/geostore/checkout': typeof GeostoreCheckoutRoute
  '/geostore/offers': typeof GeostoreOffersRoute
  '/geostore/orders': typeof GeostoreOrdersRoute
  '/geostore/rewards': typeof GeostoreRewardsRoute
  '/geostore/wishlist': typeof GeostoreWishlistRoute
  '/play/credit-history': typeof PlayCreditHistoryRoute
  '/play/daily-challenges': typeof PlayDailyChallengesRoute
  '/play/events': typeof PlayEventsRoute
  '/play/leaderboard': typeof PlayLeaderboardRoute
  '/play/level-system': typeof PlayLevelSystemRoute
  '/play/lobby': typeof PlayLobbyRoute
  '/play/matchmaking': typeof PlayMatchmakingRoute
  '/play/modes': typeof PlayModesRoute
  '/play/progression': typeof PlayProgressionRoute
  '/play/quiz': typeof PlayQuizRouteWithChildren
  '/play/rewards': typeof PlayRewardsRoute
  '/play/search': typeof PlaySearchRoute
  '/play/streak': typeof PlayStreakRoute
  '/play/weekly-challenges': typeof PlayWeeklyChallengesRoute
  '/pricing/compare': typeof PricingCompareRoute
  '/studio/analytics': typeof StudioAnalyticsRoute
  '/studio/audience': typeof StudioAudienceRoute
  '/studio/earnings': typeof StudioEarningsRoute
  '/studio/media': typeof StudioMediaRoute
  '/studio/settings': typeof StudioSettingsRoute
  '/community/': typeof CommunityIndexRoute
  '/geolibrary/': typeof GeolibraryIndexRoute
  '/geostore/': typeof GeostoreIndexRoute
  '/play/': typeof PlayIndexRoute
  '/pricing/': typeof PricingIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/_app/profile/edit': typeof AppProfileEditRoute
  '/community/member/$handle': typeof CommunityMemberHandleRoute
  '/community/post/$postId': typeof CommunityPostPostIdRoute
  '/community/topic/$slug': typeof CommunityTopicSlugRoute
  '/geolibrary/article/$slug': typeof GeolibraryArticleSlugRoute
  '/geolibrary/collections/$slug': typeof GeolibraryCollectionsSlugRoute
  '/geolibrary/creators/$handle': typeof GeolibraryCreatorsHandleRoute
  '/geostore/category/$slug': typeof GeostoreCategorySlugRoute
  '/geostore/product/$slug': typeof GeostoreProductSlugRoute
  '/play/collections/$slug': typeof PlayCollectionsSlugRoute
  '/play/history/$matchId': typeof PlayHistoryMatchIdRoute
  '/play/quiz/multiplayer': typeof PlayQuizMultiplayerRoute
  '/play/quiz/pvp': typeof PlayQuizPvpRoute
  '/play/quiz/result': typeof PlayQuizResultRoute
  '/play/quiz/review': typeof PlayQuizReviewRoute
  '/play/quiz/solo': typeof PlayQuizSoloRoute
  '/play/tournaments/$slug': typeof PlayTournamentsSlugRoute
  '/studio/articles/$articleId': typeof StudioArticlesArticleIdRoute
  '/studio/articles/new': typeof StudioArticlesNewRoute
  '/studio/quizzes/$quizId': typeof StudioQuizzesQuizIdRoute
  '/studio/quizzes/new': typeof StudioQuizzesNewRoute
  '/_app/profile/': typeof AppProfileIndexRoute
  '/geolibrary/collections/': typeof GeolibraryCollectionsIndexRoute
  '/geolibrary/creators/': typeof GeolibraryCreatorsIndexRoute
  '/play/collections/': typeof PlayCollectionsIndexRoute
  '/play/history/': typeof PlayHistoryIndexRoute
  '/play/quiz/': typeof PlayQuizIndexRoute
  '/play/tournaments/': typeof PlayTournamentsIndexRoute
  '/studio/articles/': typeof StudioArticlesIndexRoute
  '/studio/quizzes/': typeof StudioQuizzesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/about'
    | '/community'
    | '/contact'
    | '/forgot-password'
    | '/geolibrary'
    | '/geostore'
    | '/leaderboard'
    | '/library'
    | '/login'
    | '/play'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/store'
    | '/studio'
    | '/support'
    | '/terms'
    | '/achievements'
    | '/billing'
    | '/bookmarks'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/progress'
    | '/quiz-history'
    | '/settings'
    | '/auth/age-verification'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/onboarding'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/community/challenges'
    | '/community/discover'
    | '/community/events'
    | '/community/feed'
    | '/community/friends'
    | '/community/members'
    | '/community/notifications'
    | '/community/saved'
    | '/community/topics'
    | '/geolibrary/bookmarks'
    | '/geolibrary/browse'
    | '/geolibrary/progress'
    | '/geostore/browse'
    | '/geostore/cart'
    | '/geostore/checkout'
    | '/geostore/offers'
    | '/geostore/orders'
    | '/geostore/rewards'
    | '/geostore/wishlist'
    | '/play/credit-history'
    | '/play/daily-challenges'
    | '/play/events'
    | '/play/leaderboard'
    | '/play/level-system'
    | '/play/lobby'
    | '/play/matchmaking'
    | '/play/modes'
    | '/play/progression'
    | '/play/quiz'
    | '/play/rewards'
    | '/play/search'
    | '/play/streak'
    | '/play/weekly-challenges'
    | '/pricing/compare'
    | '/studio/analytics'
    | '/studio/audience'
    | '/studio/earnings'
    | '/studio/media'
    | '/studio/settings'
    | '/community/'
    | '/geolibrary/'
    | '/geostore/'
    | '/play/'
    | '/pricing/'
    | '/studio/'
    | '/profile/edit'
    | '/community/member/$handle'
    | '/community/post/$postId'
    | '/community/topic/$slug'
    | '/geolibrary/article/$slug'
    | '/geolibrary/collections/$slug'
    | '/geolibrary/creators/$handle'
    | '/geostore/category/$slug'
    | '/geostore/product/$slug'
    | '/play/collections/$slug'
    | '/play/history/$matchId'
    | '/play/quiz/multiplayer'
    | '/play/quiz/pvp'
    | '/play/quiz/result'
    | '/play/quiz/review'
    | '/play/quiz/solo'
    | '/play/tournaments/$slug'
    | '/studio/articles/$articleId'
    | '/studio/articles/new'
    | '/studio/quizzes/$quizId'
    | '/studio/quizzes/new'
    | '/profile/'
    | '/geolibrary/collections/'
    | '/geolibrary/creators/'
    | '/play/collections/'
    | '/play/history/'
    | '/play/quiz/'
    | '/play/tournaments/'
    | '/studio/articles/'
    | '/studio/quizzes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/about'
    | '/contact'
    | '/forgot-password'
    | '/leaderboard'
    | '/library'
    | '/login'
    | '/privacy'
    | '/register'
    | '/store'
    | '/support'
    | '/terms'
    | '/achievements'
    | '/billing'
    | '/bookmarks'
    | '/dashboard'
    | '/notifications'
    | '/progress'
    | '/quiz-history'
    | '/settings'
    | '/auth/age-verification'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/onboarding'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/community/challenges'
    | '/community/discover'
    | '/community/events'
    | '/community/feed'
    | '/community/friends'
    | '/community/members'
    | '/community/notifications'
    | '/community/saved'
    | '/community/topics'
    | '/geolibrary/bookmarks'
    | '/geolibrary/browse'
    | '/geolibrary/progress'
    | '/geostore/browse'
    | '/geostore/cart'
    | '/geostore/checkout'
    | '/geostore/offers'
    | '/geostore/orders'
    | '/geostore/rewards'
    | '/geostore/wishlist'
    | '/play/credit-history'
    | '/play/daily-challenges'
    | '/play/events'
    | '/play/leaderboard'
    | '/play/level-system'
    | '/play/lobby'
    | '/play/matchmaking'
    | '/play/modes'
    | '/play/progression'
    | '/play/rewards'
    | '/play/search'
    | '/play/streak'
    | '/play/weekly-challenges'
    | '/pricing/compare'
    | '/studio/analytics'
    | '/studio/audience'
    | '/studio/earnings'
    | '/studio/media'
    | '/studio/settings'
    | '/community'
    | '/geolibrary'
    | '/geostore'
    | '/play'
    | '/pricing'
    | '/studio'
    | '/profile/edit'
    | '/community/member/$handle'
    | '/community/post/$postId'
    | '/community/topic/$slug'
    | '/geolibrary/article/$slug'
    | '/geolibrary/collections/$slug'
    | '/geolibrary/creators/$handle'
    | '/geostore/category/$slug'
    | '/geostore/product/$slug'
    | '/play/collections/$slug'
    | '/play/history/$matchId'
    | '/play/quiz/multiplayer'
    | '/play/quiz/pvp'
    | '/play/quiz/result'
    | '/play/quiz/review'
    | '/play/quiz/solo'
    | '/play/tournaments/$slug'
    | '/studio/articles/$articleId'
    | '/studio/articles/new'
    | '/studio/quizzes/$quizId'
    | '/studio/quizzes/new'
    | '/profile'
    | '/geolibrary/collections'
    | '/geolibrary/creators'
    | '/play/collections'
    | '/play/history'
    | '/play/quiz'
    | '/play/tournaments'
    | '/studio/articles'
    | '/studio/quizzes'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/_app'
    | '/about'
    | '/community'
    | '/contact'
    | '/forgot-password'
    | '/geolibrary'
    | '/geostore'
    | '/leaderboard'
    | '/library'
    | '/login'
    | '/play'
    | '/pricing'
    | '/privacy'
    | '/register'
    | '/store'
    | '/studio'
    | '/support'
    | '/terms'
    | '/_app/achievements'
    | '/_app/billing'
    | '/_app/bookmarks'
    | '/_app/dashboard'
    | '/_app/notifications'
    | '/_app/profile'
    | '/_app/progress'
    | '/_app/quiz-history'
    | '/_app/settings'
    | '/auth/age-verification'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/onboarding'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/community/challenges'
    | '/community/discover'
    | '/community/events'
    | '/community/feed'
    | '/community/friends'
    | '/community/members'
    | '/community/notifications'
    | '/community/saved'
    | '/community/topics'
    | '/geolibrary/bookmarks'
    | '/geolibrary/browse'
    | '/geolibrary/progress'
    | '/geostore/browse'
    | '/geostore/cart'
    | '/geostore/checkout'
    | '/geostore/offers'
    | '/geostore/orders'
    | '/geostore/rewards'
    | '/geostore/wishlist'
    | '/play/credit-history'
    | '/play/daily-challenges'
    | '/play/events'
    | '/play/leaderboard'
    | '/play/level-system'
    | '/play/lobby'
    | '/play/matchmaking'
    | '/play/modes'
    | '/play/progression'
    | '/play/quiz'
    | '/play/rewards'
    | '/play/search'
    | '/play/streak'
    | '/play/weekly-challenges'
    | '/pricing/compare'
    | '/studio/analytics'
    | '/studio/audience'
    | '/studio/earnings'
    | '/studio/media'
    | '/studio/settings'
    | '/community/'
    | '/geolibrary/'
    | '/geostore/'
    | '/play/'
    | '/pricing/'
    | '/studio/'
    | '/_app/profile/edit'
    | '/community/member/$handle'
    | '/community/post/$postId'
    | '/community/topic/$slug'
    | '/geolibrary/article/$slug'
    | '/geolibrary/collections/$slug'
    | '/geolibrary/creators/$handle'
    | '/geostore/category/$slug'
    | '/geostore/product/$slug'
    | '/play/collections/$slug'
    | '/play/history/$matchId'
    | '/play/quiz/multiplayer'
    | '/play/quiz/pvp'
    | '/play/quiz/result'
    | '/play/quiz/review'
    | '/play/quiz/solo'
    | '/play/tournaments/$slug'
    | '/studio/articles/$articleId'
    | '/studio/articles/new'
    | '/studio/quizzes/$quizId'
    | '/studio/quizzes/new'
    | '/_app/profile/'
    | '/geolibrary/collections/'
    | '/geolibrary/creators/'
    | '/play/collections/'
    | '/play/history/'
    | '/play/quiz/'
    | '/play/tournaments/'
    | '/studio/articles/'
    | '/studio/quizzes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AppRoute: typeof AppRouteWithChildren
  AboutRoute: typeof AboutRoute
  CommunityRoute: typeof CommunityRouteWithChildren
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GeolibraryRoute: typeof GeolibraryRouteWithChildren
  GeostoreRoute: typeof GeostoreRouteWithChildren
  LeaderboardRoute: typeof LeaderboardRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  PlayRoute: typeof PlayRouteWithChildren
  PricingRoute: typeof PricingRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  StoreRoute: typeof StoreRoute
  StudioRoute: typeof StudioRouteWithChildren
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  AuthAgeVerificationRoute: typeof AuthAgeVerificationRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOnboardingRoute: typeof AuthOnboardingRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geolibrary': {
      id: '/geolibrary'
      path: '/geolibrary'
      fullPath: '/geolibrary'
      preLoaderRoute: typeof GeolibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geostore': {
      id: '/geostore'
      path: '/geostore'
      fullPath: '/geostore'
      preLoaderRoute: typeof GeostoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/achievements': {
      id: '/_app/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AppAchievementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bookmarks': {
      id: '/_app/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof AppBookmarksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/progress': {
      id: '/_app/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quiz-history': {
      id: '/_app/quiz-history'
      path: '/quiz-history'
      fullPath: '/quiz-history'
      preLoaderRoute: typeof AppQuizHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/age-verification': {
      id: '/auth/age-verification'
      path: '/auth/age-verification'
      fullPath: '/auth/age-verification'
      preLoaderRoute: typeof AuthAgeVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/onboarding': {
      id: '/auth/onboarding'
      path: '/auth/onboarding'
      fullPath: '/auth/onboarding'
      preLoaderRoute: typeof AuthOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/': {
      id: '/community/'
      path: '/'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/community/challenges': {
      id: '/community/challenges'
      path: '/challenges'
      fullPath: '/community/challenges'
      preLoaderRoute: typeof CommunityChallengesRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/community/discover': {
      id: '/community/discover'
      path: '/discover'
      fullPath: '/community/discover'
      preLoaderRoute: typeof CommunityDiscoverRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/community/events': {
      id: '/community/events'
      path: '/events'
      fullPath: '/community/events'
      preLoaderRoute: typeof CommunityEventsRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/community/feed': {
      id: '/community/feed'
      path: '/feed'
      fullPath: '/community/feed'
      preLoaderRoute: typeof CommunityFeedRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/community/friends': {
      id: '/community/friends'
      path: '/friends'
      fullPath: '/community/friends'
      preLoaderRoute: typeof CommunityFriendsRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/community/members': {
      id: '/community/members'
      path: '/members'
      fullPath: '/community/members'
      preLoaderRoute: typeof CommunityMembersRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/community/notifications': {
      id: '/community/notifications'
      path: '/notifications'
      fullPath: '/community/notifications'
      preLoaderRoute: typeof CommunityNotificationsRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/community/saved': {
      id: '/community/saved'
      path: '/saved'
      fullPath: '/community/saved'
      preLoaderRoute: typeof CommunitySavedRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/community/topics': {
      id: '/community/topics'
      path: '/topics'
      fullPath: '/community/topics'
      preLoaderRoute: typeof CommunityTopicsRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/geolibrary/': {
      id: '/geolibrary/'
      path: '/'
      fullPath: '/geolibrary/'
      preLoaderRoute: typeof GeolibraryIndexRouteImport
      parentRoute: typeof GeolibraryRoute
    }
    '/geolibrary/bookmarks': {
      id: '/geolibrary/bookmarks'
      path: '/bookmarks'
      fullPath: '/geolibrary/bookmarks'
      preLoaderRoute: typeof GeolibraryBookmarksRouteImport
      parentRoute: typeof GeolibraryRoute
    }
    '/geolibrary/browse': {
      id: '/geolibrary/browse'
      path: '/browse'
      fullPath: '/geolibrary/browse'
      preLoaderRoute: typeof GeolibraryBrowseRouteImport
      parentRoute: typeof GeolibraryRoute
    }
    '/geolibrary/progress': {
      id: '/geolibrary/progress'
      path: '/progress'
      fullPath: '/geolibrary/progress'
      preLoaderRoute: typeof GeolibraryProgressRouteImport
      parentRoute: typeof GeolibraryRoute
    }
    '/geostore/': {
      id: '/geostore/'
      path: '/'
      fullPath: '/geostore/'
      preLoaderRoute: typeof GeostoreIndexRouteImport
      parentRoute: typeof GeostoreRoute
    }
    '/geostore/browse': {
      id: '/geostore/browse'
      path: '/browse'
      fullPath: '/geostore/browse'
      preLoaderRoute: typeof GeostoreBrowseRouteImport
      parentRoute: typeof GeostoreRoute
    }
    '/geostore/cart': {
      id: '/geostore/cart'
      path: '/cart'
      fullPath: '/geostore/cart'
      preLoaderRoute: typeof GeostoreCartRouteImport
      parentRoute: typeof GeostoreRoute
    }
    '/geostore/checkout': {
      id: '/geostore/checkout'
      path: '/checkout'
      fullPath: '/geostore/checkout'
      preLoaderRoute: typeof GeostoreCheckoutRouteImport
      parentRoute: typeof GeostoreRoute
    }
    '/geostore/offers': {
      id: '/geostore/offers'
      path: '/offers'
      fullPath: '/geostore/offers'
      preLoaderRoute: typeof GeostoreOffersRouteImport
      parentRoute: typeof GeostoreRoute
    }
    '/geostore/orders': {
      id: '/geostore/orders'
      path: '/orders'
      fullPath: '/geostore/orders'
      preLoaderRoute: typeof GeostoreOrdersRouteImport
      parentRoute: typeof GeostoreRoute
    }
    '/geostore/rewards': {
      id: '/geostore/rewards'
      path: '/rewards'
      fullPath: '/geostore/rewards'
      preLoaderRoute: typeof GeostoreRewardsRouteImport
      parentRoute: typeof GeostoreRoute
    }
    '/geostore/wishlist': {
      id: '/geostore/wishlist'
      path: '/wishlist'
      fullPath: '/geostore/wishlist'
      preLoaderRoute: typeof GeostoreWishlistRouteImport
      parentRoute: typeof GeostoreRoute
    }
    '/play/': {
      id: '/play/'
      path: '/'
      fullPath: '/play/'
      preLoaderRoute: typeof PlayIndexRouteImport
      parentRoute: typeof PlayRoute
    }
    '/play/credit-history': {
      id: '/play/credit-history'
      path: '/credit-history'
      fullPath: '/play/credit-history'
      preLoaderRoute: typeof PlayCreditHistoryRouteImport
      parentRoute: typeof PlayRoute
    }
    '/play/daily-challenges': {
      id: '/play/daily-challenges'
      path: '/daily-challenges'
      fullPath: '/play/daily-challenges'
      preLoaderRoute: typeof PlayDailyChallengesRouteImport
      parentRoute: typeof PlayRoute
    }
    '/play/events': {
      id: '/play/events'
      path: '/events'
      fullPath: '/play/events'
      preLoaderRoute: typeof PlayEventsRouteImport
      parentRoute: typeof PlayRoute
    }
    '/play/leaderboard': {
      id: '/play/leaderboard'
      path: '/leaderboard'
      fullPath: '/play/leaderboard'
      preLoaderRoute: typeof PlayLeaderboardRouteImport
      parentRoute: typeof PlayRoute
    }
    '/play/level-system': {
      id: '/play/level-system'
      path: '/level-system'
      fullPath: '/play/level-system'
      preLoaderRoute: typeof PlayLevelSystemRouteImport
      parentRoute: typeof PlayRoute
    }
    '/play/lobby': {
      id: '/play/lobby'
      path: '/lobby'
      fullPath: '/play/lobby'
      preLoaderRoute: typeof PlayLobbyRouteImport
      parentRoute: typeof PlayRoute
    }
    '/play/matchmaking': {
      id: '/play/matchmaking'
      path: '/matchmaking'
      fullPath: '/play/matchmaking'
      preLoaderRoute: typeof PlayMatchmakingRouteImport
      parentRoute: typeof PlayRoute
    }
    '/play/modes': {
      id: '/play/modes'
      path: '/modes'
      fullPath: '/play/modes'
      preLoaderRoute: typeof PlayModesRouteImport
      parentRoute: typeof PlayRoute
    }
    '/play/progression': {
      id: '/play/progression'
      path: '/progression'
      fullPath: '/play/progression'
      preLoaderRoute: typeof PlayProgressionRouteImport
      parentRoute: typeof PlayRoute
    }
    '/play/quiz': {
      id: '/play/quiz'
      path: '/quiz'
      fullPath: '/play/quiz'
      preLoaderRoute: typeof PlayQuizRouteImport
      parentRoute: typeof PlayRoute
    }
    '/play/rewards': {
      id: '/play/rewards'
      path: '/rewards'
      fullPath: '/play/rewards'
      preLoaderRoute: typeof PlayRewardsRouteImport
      parentRoute: typeof PlayRoute
    }
    '/play/search': {
      id: '/play/search'
      path: '/search'
      fullPath: '/play/search'
      preLoaderRoute: typeof PlaySearchRouteImport
      parentRoute: typeof PlayRoute
    }
    '/play/streak': {
      id: '/play/streak'
      path: '/streak'
      fullPath: '/play/streak'
      preLoaderRoute: typeof PlayStreakRouteImport
      parentRoute: typeof PlayRoute
    }
    '/play/weekly-challenges': {
      id: '/play/weekly-challenges'
      path: '/weekly-challenges'
      fullPath: '/play/weekly-challenges'
      preLoaderRoute: typeof PlayWeeklyChallengesRouteImport
      parentRoute: typeof PlayRoute
    }
    '/pricing/': {
      id: '/pricing/'
      path: '/'
      fullPath: '/pricing/'
      preLoaderRoute: typeof PricingIndexRouteImport
      parentRoute: typeof PricingRoute
    }
    '/pricing/compare': {
      id: '/pricing/compare'
      path: '/compare'
      fullPath: '/pricing/compare'
      preLoaderRoute: typeof PricingCompareRouteImport
      parentRoute: typeof PricingRoute
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/analytics': {
      id: '/studio/analytics'
      path: '/analytics'
      fullPath: '/studio/analytics'
      preLoaderRoute: typeof StudioAnalyticsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/audience': {
      id: '/studio/audience'
      path: '/audience'
      fullPath: '/studio/audience'
      preLoaderRoute: typeof StudioAudienceRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/earnings': {
      id: '/studio/earnings'
      path: '/earnings'
      fullPath: '/studio/earnings'
      preLoaderRoute: typeof StudioEarningsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/media': {
      id: '/studio/media'
      path: '/media'
      fullPath: '/studio/media'
      preLoaderRoute: typeof StudioMediaRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/settings': {
      id: '/studio/settings'
      path: '/settings'
      fullPath: '/studio/settings'
      preLoaderRoute: typeof StudioSettingsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_app/profile/': {
      id: '/_app/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/_app/profile/edit': {
      id: '/_app/profile/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof AppProfileEditRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/community/member/$handle': {
      id: '/community/member/$handle'
      path: '/member/$handle'
      fullPath: '/community/member/$handle'
      preLoaderRoute: typeof CommunityMemberHandleRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/community/post/$postId': {
      id: '/community/post/$postId'
      path: '/post/$postId'
      fullPath: '/community/post/$postId'
      preLoaderRoute: typeof CommunityPostPostIdRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/community/topic/$slug': {
      id: '/community/topic/$slug'
      path: '/topic/$slug'
      fullPath: '/community/topic/$slug'
      preLoaderRoute: typeof CommunityTopicSlugRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/geolibrary/article/$slug': {
      id: '/geolibrary/article/$slug'
      path: '/article/$slug'
      fullPath: '/geolibrary/article/$slug'
      preLoaderRoute: typeof GeolibraryArticleSlugRouteImport
      parentRoute: typeof GeolibraryRoute
    }
    '/geolibrary/collections/': {
      id: '/geolibrary/collections/'
      path: '/collections'
      fullPath: '/geolibrary/collections/'
      preLoaderRoute: typeof GeolibraryCollectionsIndexRouteImport
      parentRoute: typeof GeolibraryRoute
    }
    '/geolibrary/collections/$slug': {
      id: '/geolibrary/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/geolibrary/collections/$slug'
      preLoaderRoute: typeof GeolibraryCollectionsSlugRouteImport
      parentRoute: typeof GeolibraryRoute
    }
    '/geolibrary/creators/': {
      id: '/geolibrary/creators/'
      path: '/creators'
      fullPath: '/geolibrary/creators/'
      preLoaderRoute: typeof GeolibraryCreatorsIndexRouteImport
      parentRoute: typeof GeolibraryRoute
    }
    '/geolibrary/creators/$handle': {
      id: '/geolibrary/creators/$handle'
      path: '/creators/$handle'
      fullPath: '/geolibrary/creators/$handle'
      preLoaderRoute: typeof GeolibraryCreatorsHandleRouteImport
      parentRoute: typeof GeolibraryRoute
    }
    '/geostore/category/$slug': {
      id: '/geostore/category/$slug'
      path: '/category/$slug'
      fullPath: '/geostore/category/$slug'
      preLoaderRoute: typeof GeostoreCategorySlugRouteImport
      parentRoute: typeof GeostoreRoute
    }
    '/geostore/product/$slug': {
      id: '/geostore/product/$slug'
      path: '/product/$slug'
      fullPath: '/geostore/product/$slug'
      preLoaderRoute: typeof GeostoreProductSlugRouteImport
      parentRoute: typeof GeostoreRoute
    }
    '/play/collections/': {
      id: '/play/collections/'
      path: '/collections'
      fullPath: '/play/collections/'
      preLoaderRoute: typeof PlayCollectionsIndexRouteImport
      parentRoute: typeof PlayRoute
    }
    '/play/collections/$slug': {
      id: '/play/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/play/collections/$slug'
      preLoaderRoute: typeof PlayCollectionsSlugRouteImport
      parentRoute: typeof PlayRoute
    }
    '/play/history/': {
      id: '/play/history/'
      path: '/history'
      fullPath: '/play/history/'
      preLoaderRoute: typeof PlayHistoryIndexRouteImport
      parentRoute: typeof PlayRoute
    }
    '/play/history/$matchId': {
      id: '/play/history/$matchId'
      path: '/history/$matchId'
      fullPath: '/play/history/$matchId'
      preLoaderRoute: typeof PlayHistoryMatchIdRouteImport
      parentRoute: typeof PlayRoute
    }
    '/play/quiz/': {
      id: '/play/quiz/'
      path: '/'
      fullPath: '/play/quiz/'
      preLoaderRoute: typeof PlayQuizIndexRouteImport
      parentRoute: typeof PlayQuizRoute
    }
    '/play/quiz/multiplayer': {
      id: '/play/quiz/multiplayer'
      path: '/multiplayer'
      fullPath: '/play/quiz/multiplayer'
      preLoaderRoute: typeof PlayQuizMultiplayerRouteImport
      parentRoute: typeof PlayQuizRoute
    }
    '/play/quiz/pvp': {
      id: '/play/quiz/pvp'
      path: '/pvp'
      fullPath: '/play/quiz/pvp'
      preLoaderRoute: typeof PlayQuizPvpRouteImport
      parentRoute: typeof PlayQuizRoute
    }
    '/play/quiz/result': {
      id: '/play/quiz/result'
      path: '/result'
      fullPath: '/play/quiz/result'
      preLoaderRoute: typeof PlayQuizResultRouteImport
      parentRoute: typeof PlayQuizRoute
    }
    '/play/quiz/review': {
      id: '/play/quiz/review'
      path: '/review'
      fullPath: '/play/quiz/review'
      preLoaderRoute: typeof PlayQuizReviewRouteImport
      parentRoute: typeof PlayQuizRoute
    }
    '/play/quiz/solo': {
      id: '/play/quiz/solo'
      path: '/solo'
      fullPath: '/play/quiz/solo'
      preLoaderRoute: typeof PlayQuizSoloRouteImport
      parentRoute: typeof PlayQuizRoute
    }
    '/play/tournaments/': {
      id: '/play/tournaments/'
      path: '/tournaments'
      fullPath: '/play/tournaments/'
      preLoaderRoute: typeof PlayTournamentsIndexRouteImport
      parentRoute: typeof PlayRoute
    }
    '/play/tournaments/$slug': {
      id: '/play/tournaments/$slug'
      path: '/tournaments/$slug'
      fullPath: '/play/tournaments/$slug'
      preLoaderRoute: typeof PlayTournamentsSlugRouteImport
      parentRoute: typeof PlayRoute
    }
    '/studio/articles/': {
      id: '/studio/articles/'
      path: '/articles'
      fullPath: '/studio/articles/'
      preLoaderRoute: typeof StudioArticlesIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/articles/$articleId': {
      id: '/studio/articles/$articleId'
      path: '/articles/$articleId'
      fullPath: '/studio/articles/$articleId'
      preLoaderRoute: typeof StudioArticlesArticleIdRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/articles/new': {
      id: '/studio/articles/new'
      path: '/articles/new'
      fullPath: '/studio/articles/new'
      preLoaderRoute: typeof StudioArticlesNewRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/quizzes/': {
      id: '/studio/quizzes/'
      path: '/quizzes'
      fullPath: '/studio/quizzes/'
      preLoaderRoute: typeof StudioQuizzesIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/quizzes/$quizId': {
      id: '/studio/quizzes/$quizId'
      path: '/quizzes/$quizId'
      fullPath: '/studio/quizzes/$quizId'
      preLoaderRoute: typeof StudioQuizzesQuizIdRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/quizzes/new': {
      id: '/studio/quizzes/new'
      path: '/quizzes/new'
      fullPath: '/studio/quizzes/new'
      preLoaderRoute: typeof StudioQuizzesNewRouteImport
      parentRoute: typeof StudioRoute
    }
  }
}

interface AppProfileRouteChildren {
  AppProfileEditRoute: typeof AppProfileEditRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
}

const AppProfileRouteChildren: AppProfileRouteChildren = {
  AppProfileEditRoute: AppProfileEditRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
}

const AppProfileRouteWithChildren = AppProfileRoute._addFileChildren(
  AppProfileRouteChildren,
)

interface AppRouteChildren {
  AppAchievementsRoute: typeof AppAchievementsRoute
  AppBillingRoute: typeof AppBillingRoute
  AppBookmarksRoute: typeof AppBookmarksRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRouteWithChildren
  AppProgressRoute: typeof AppProgressRoute
  AppQuizHistoryRoute: typeof AppQuizHistoryRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAchievementsRoute: AppAchievementsRoute,
  AppBillingRoute: AppBillingRoute,
  AppBookmarksRoute: AppBookmarksRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRouteWithChildren,
  AppProgressRoute: AppProgressRoute,
  AppQuizHistoryRoute: AppQuizHistoryRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface CommunityRouteChildren {
  CommunityChallengesRoute: typeof CommunityChallengesRoute
  CommunityDiscoverRoute: typeof CommunityDiscoverRoute
  CommunityEventsRoute: typeof CommunityEventsRoute
  CommunityFeedRoute: typeof CommunityFeedRoute
  CommunityFriendsRoute: typeof CommunityFriendsRoute
  CommunityMembersRoute: typeof CommunityMembersRoute
  CommunityNotificationsRoute: typeof CommunityNotificationsRoute
  CommunitySavedRoute: typeof CommunitySavedRoute
  CommunityTopicsRoute: typeof CommunityTopicsRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
  CommunityMemberHandleRoute: typeof CommunityMemberHandleRoute
  CommunityPostPostIdRoute: typeof CommunityPostPostIdRoute
  CommunityTopicSlugRoute: typeof CommunityTopicSlugRoute
}

const CommunityRouteChildren: CommunityRouteChildren = {
  CommunityChallengesRoute: CommunityChallengesRoute,
  CommunityDiscoverRoute: CommunityDiscoverRoute,
  CommunityEventsRoute: CommunityEventsRoute,
  CommunityFeedRoute: CommunityFeedRoute,
  CommunityFriendsRoute: CommunityFriendsRoute,
  CommunityMembersRoute: CommunityMembersRoute,
  CommunityNotificationsRoute: CommunityNotificationsRoute,
  CommunitySavedRoute: CommunitySavedRoute,
  CommunityTopicsRoute: CommunityTopicsRoute,
  CommunityIndexRoute: CommunityIndexRoute,
  CommunityMemberHandleRoute: CommunityMemberHandleRoute,
  CommunityPostPostIdRoute: CommunityPostPostIdRoute,
  CommunityTopicSlugRoute: CommunityTopicSlugRoute,
}

const CommunityRouteWithChildren = CommunityRoute._addFileChildren(
  CommunityRouteChildren,
)

interface GeolibraryRouteChildren {
  GeolibraryBookmarksRoute: typeof GeolibraryBookmarksRoute
  GeolibraryBrowseRoute: typeof GeolibraryBrowseRoute
  GeolibraryProgressRoute: typeof GeolibraryProgressRoute
  GeolibraryIndexRoute: typeof GeolibraryIndexRoute
  GeolibraryArticleSlugRoute: typeof GeolibraryArticleSlugRoute
  GeolibraryCollectionsSlugRoute: typeof GeolibraryCollectionsSlugRoute
  GeolibraryCreatorsHandleRoute: typeof GeolibraryCreatorsHandleRoute
  GeolibraryCollectionsIndexRoute: typeof GeolibraryCollectionsIndexRoute
  GeolibraryCreatorsIndexRoute: typeof GeolibraryCreatorsIndexRoute
}

const GeolibraryRouteChildren: GeolibraryRouteChildren = {
  GeolibraryBookmarksRoute: GeolibraryBookmarksRoute,
  GeolibraryBrowseRoute: GeolibraryBrowseRoute,
  GeolibraryProgressRoute: GeolibraryProgressRoute,
  GeolibraryIndexRoute: GeolibraryIndexRoute,
  GeolibraryArticleSlugRoute: GeolibraryArticleSlugRoute,
  GeolibraryCollectionsSlugRoute: GeolibraryCollectionsSlugRoute,
  GeolibraryCreatorsHandleRoute: GeolibraryCreatorsHandleRoute,
  GeolibraryCollectionsIndexRoute: GeolibraryCollectionsIndexRoute,
  GeolibraryCreatorsIndexRoute: GeolibraryCreatorsIndexRoute,
}

const GeolibraryRouteWithChildren = GeolibraryRoute._addFileChildren(
  GeolibraryRouteChildren,
)

interface GeostoreRouteChildren {
  GeostoreBrowseRoute: typeof GeostoreBrowseRoute
  GeostoreCartRoute: typeof GeostoreCartRoute
  GeostoreCheckoutRoute: typeof GeostoreCheckoutRoute
  GeostoreOffersRoute: typeof GeostoreOffersRoute
  GeostoreOrdersRoute: typeof GeostoreOrdersRoute
  GeostoreRewardsRoute: typeof GeostoreRewardsRoute
  GeostoreWishlistRoute: typeof GeostoreWishlistRoute
  GeostoreIndexRoute: typeof GeostoreIndexRoute
  GeostoreCategorySlugRoute: typeof GeostoreCategorySlugRoute
  GeostoreProductSlugRoute: typeof GeostoreProductSlugRoute
}

const GeostoreRouteChildren: GeostoreRouteChildren = {
  GeostoreBrowseRoute: GeostoreBrowseRoute,
  GeostoreCartRoute: GeostoreCartRoute,
  GeostoreCheckoutRoute: GeostoreCheckoutRoute,
  GeostoreOffersRoute: GeostoreOffersRoute,
  GeostoreOrdersRoute: GeostoreOrdersRoute,
  GeostoreRewardsRoute: GeostoreRewardsRoute,
  GeostoreWishlistRoute: GeostoreWishlistRoute,
  GeostoreIndexRoute: GeostoreIndexRoute,
  GeostoreCategorySlugRoute: GeostoreCategorySlugRoute,
  GeostoreProductSlugRoute: GeostoreProductSlugRoute,
}

const GeostoreRouteWithChildren = GeostoreRoute._addFileChildren(
  GeostoreRouteChildren,
)

interface PlayQuizRouteChildren {
  PlayQuizMultiplayerRoute: typeof PlayQuizMultiplayerRoute
  PlayQuizPvpRoute: typeof PlayQuizPvpRoute
  PlayQuizResultRoute: typeof PlayQuizResultRoute
  PlayQuizReviewRoute: typeof PlayQuizReviewRoute
  PlayQuizSoloRoute: typeof PlayQuizSoloRoute
  PlayQuizIndexRoute: typeof PlayQuizIndexRoute
}

const PlayQuizRouteChildren: PlayQuizRouteChildren = {
  PlayQuizMultiplayerRoute: PlayQuizMultiplayerRoute,
  PlayQuizPvpRoute: PlayQuizPvpRoute,
  PlayQuizResultRoute: PlayQuizResultRoute,
  PlayQuizReviewRoute: PlayQuizReviewRoute,
  PlayQuizSoloRoute: PlayQuizSoloRoute,
  PlayQuizIndexRoute: PlayQuizIndexRoute,
}

const PlayQuizRouteWithChildren = PlayQuizRoute._addFileChildren(
  PlayQuizRouteChildren,
)

interface PlayRouteChildren {
  PlayCreditHistoryRoute: typeof PlayCreditHistoryRoute
  PlayDailyChallengesRoute: typeof PlayDailyChallengesRoute
  PlayEventsRoute: typeof PlayEventsRoute
  PlayLeaderboardRoute: typeof PlayLeaderboardRoute
  PlayLevelSystemRoute: typeof PlayLevelSystemRoute
  PlayLobbyRoute: typeof PlayLobbyRoute
  PlayMatchmakingRoute: typeof PlayMatchmakingRoute
  PlayModesRoute: typeof PlayModesRoute
  PlayProgressionRoute: typeof PlayProgressionRoute
  PlayQuizRoute: typeof PlayQuizRouteWithChildren
  PlayRewardsRoute: typeof PlayRewardsRoute
  PlaySearchRoute: typeof PlaySearchRoute
  PlayStreakRoute: typeof PlayStreakRoute
  PlayWeeklyChallengesRoute: typeof PlayWeeklyChallengesRoute
  PlayIndexRoute: typeof PlayIndexRoute
  PlayCollectionsSlugRoute: typeof PlayCollectionsSlugRoute
  PlayHistoryMatchIdRoute: typeof PlayHistoryMatchIdRoute
  PlayTournamentsSlugRoute: typeof PlayTournamentsSlugRoute
  PlayCollectionsIndexRoute: typeof PlayCollectionsIndexRoute
  PlayHistoryIndexRoute: typeof PlayHistoryIndexRoute
  PlayTournamentsIndexRoute: typeof PlayTournamentsIndexRoute
}

const PlayRouteChildren: PlayRouteChildren = {
  PlayCreditHistoryRoute: PlayCreditHistoryRoute,
  PlayDailyChallengesRoute: PlayDailyChallengesRoute,
  PlayEventsRoute: PlayEventsRoute,
  PlayLeaderboardRoute: PlayLeaderboardRoute,
  PlayLevelSystemRoute: PlayLevelSystemRoute,
  PlayLobbyRoute: PlayLobbyRoute,
  PlayMatchmakingRoute: PlayMatchmakingRoute,
  PlayModesRoute: PlayModesRoute,
  PlayProgressionRoute: PlayProgressionRoute,
  PlayQuizRoute: PlayQuizRouteWithChildren,
  PlayRewardsRoute: PlayRewardsRoute,
  PlaySearchRoute: PlaySearchRoute,
  PlayStreakRoute: PlayStreakRoute,
  PlayWeeklyChallengesRoute: PlayWeeklyChallengesRoute,
  PlayIndexRoute: PlayIndexRoute,
  PlayCollectionsSlugRoute: PlayCollectionsSlugRoute,
  PlayHistoryMatchIdRoute: PlayHistoryMatchIdRoute,
  PlayTournamentsSlugRoute: PlayTournamentsSlugRoute,
  PlayCollectionsIndexRoute: PlayCollectionsIndexRoute,
  PlayHistoryIndexRoute: PlayHistoryIndexRoute,
  PlayTournamentsIndexRoute: PlayTournamentsIndexRoute,
}

const PlayRouteWithChildren = PlayRoute._addFileChildren(PlayRouteChildren)

interface PricingRouteChildren {
  PricingCompareRoute: typeof PricingCompareRoute
  PricingIndexRoute: typeof PricingIndexRoute
}

const PricingRouteChildren: PricingRouteChildren = {
  PricingCompareRoute: PricingCompareRoute,
  PricingIndexRoute: PricingIndexRoute,
}

const PricingRouteWithChildren =
  PricingRoute._addFileChildren(PricingRouteChildren)

interface StudioRouteChildren {
  StudioAnalyticsRoute: typeof StudioAnalyticsRoute
  StudioAudienceRoute: typeof StudioAudienceRoute
  StudioEarningsRoute: typeof StudioEarningsRoute
  StudioMediaRoute: typeof StudioMediaRoute
  StudioSettingsRoute: typeof StudioSettingsRoute
  StudioIndexRoute: typeof StudioIndexRoute
  StudioArticlesArticleIdRoute: typeof StudioArticlesArticleIdRoute
  StudioArticlesNewRoute: typeof StudioArticlesNewRoute
  StudioQuizzesQuizIdRoute: typeof StudioQuizzesQuizIdRoute
  StudioQuizzesNewRoute: typeof StudioQuizzesNewRoute
  StudioArticlesIndexRoute: typeof StudioArticlesIndexRoute
  StudioQuizzesIndexRoute: typeof StudioQuizzesIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioAnalyticsRoute: StudioAnalyticsRoute,
  StudioAudienceRoute: StudioAudienceRoute,
  StudioEarningsRoute: StudioEarningsRoute,
  StudioMediaRoute: StudioMediaRoute,
  StudioSettingsRoute: StudioSettingsRoute,
  StudioIndexRoute: StudioIndexRoute,
  StudioArticlesArticleIdRoute: StudioArticlesArticleIdRoute,
  StudioArticlesNewRoute: StudioArticlesNewRoute,
  StudioQuizzesQuizIdRoute: StudioQuizzesQuizIdRoute,
  StudioQuizzesNewRoute: StudioQuizzesNewRoute,
  StudioArticlesIndexRoute: StudioArticlesIndexRoute,
  StudioQuizzesIndexRoute: StudioQuizzesIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AppRoute: AppRouteWithChildren,
  AboutRoute: AboutRoute,
  CommunityRoute: CommunityRouteWithChildren,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GeolibraryRoute: GeolibraryRouteWithChildren,
  GeostoreRoute: GeostoreRouteWithChildren,
  LeaderboardRoute: LeaderboardRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  PlayRoute: PlayRouteWithChildren,
  PricingRoute: PricingRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  StoreRoute: StoreRoute,
  StudioRoute: StudioRouteWithChildren,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  AuthAgeVerificationRoute: AuthAgeVerificationRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthOnboardingRoute: AuthOnboardingRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
